/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view.caixa;

import com.newBig.system.controller.HelpController;
import com.newBig.system.controller.batch.BatchControllerInterface;
import com.newBig.system.controller.batch.impl.BatchControllerImpl;
import com.newBig.system.model.service.*;
import com.newBig.system.view.inicio.TelaInicio;
import com.newBig.system.view.login.TelaLogin;
import com.newBig.system.view.batch.ArrivalBatchView;
import com.newBig.system.view.cliente.TelaCliente;
import com.newBig.system.view.funcionario.TelaFuncionario;
import com.newBig.system.view.product.ProductView;
import com.newBig.system.view.sale.SalesView;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author mourv
 */
public class TelaCaixa extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCaixa.class.getName());
    Caixa caixa = new Caixa();
    DadosUsuario dadosUsuario = new DadosUsuario();
    Login login = new Login();
    private HelpService helpService;
    private final HelpController helpController;
    //teste
    private final BatchControllerInterface batchController;

    /**
     * Creates new form TelaCaixa
     */
    public TelaCaixa(HelpService helpService, BatchControllerInterface batchController, HelpController helpController) {
        this.helpService = helpService;
        this.helpController = helpController;
        this.batchController = batchController;
        initComponents();
        logoUsuario();
        logoNewBig();
        LgNome.setText(login.nomeLog());
        LgAcesso.setText(login.acessoLog());
        this.setLocationRelativeTo(null);
        preencherValores();
        preencherLog();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        fundoValorAtual = new javax.swing.JPanel();
        subtitulo = new javax.swing.JLabel();
        valorAtual = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fundoAbertura = new javax.swing.JPanel();
        valorAbertura = new javax.swing.JLabel();
        subtitulo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        subtitulo2 = new javax.swing.JLabel();
        valorEntrada = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logs = new javax.swing.JTextArea();
        titulocaixa = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        logsDoCaixa = new javax.swing.JLabel();
        fundoDados = new javax.swing.JPanel();
        topicos = new javax.swing.JLabel();
        txtdata = new javax.swing.JLabel();
        topicos1 = new javax.swing.JLabel();
        txthora = new javax.swing.JLabel();
        topicos2 = new javax.swing.JLabel();
        txtuser = new javax.swing.JLabel();
        topicos3 = new javax.swing.JLabel();
        txtsangria = new javax.swing.JLabel();
        btnSangria = new javax.swing.JButton();
        menuLateral = new javax.swing.JPanel();
        NBLogo = new javax.swing.JLabel();
        menuLTitulo = new javax.swing.JLabel();
        btnCaixa = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        btnClientes1 = new javax.swing.JButton();
        btnLote = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        LgNome = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        LgAcesso = new javax.swing.JLabel();
        MenuBarra = new javax.swing.JMenuBar();
        menuBar = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        fundo.setBackground(new java.awt.Color(255, 249, 249));
        fundo.setToolTipText("");
        fundo.setPreferredSize(new java.awt.Dimension(760, 498));
        fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titulo.setText("Caixa");
        fundo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, 78, 54));

        fundoValorAtual.setBackground(new java.awt.Color(255, 255, 255));
        fundoValorAtual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fundoValorAtual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitulo.setText("Valor atual");
        fundoValorAtual.add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, -1));

        valorAtual.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        valorAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorAtual.setText("R$10.009,00");
        fundoValorAtual.add(valorAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 64));

        jPanel1.setBackground(new java.awt.Color(94, 110, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
        );

        fundoValorAtual.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        fundo.add(fundoValorAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 225, 106));

        fundoAbertura.setBackground(new java.awt.Color(255, 255, 255));
        fundoAbertura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fundoAbertura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorAbertura.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        valorAbertura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorAbertura.setText("R$10.009,00");
        fundoAbertura.add(valorAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, -1, 54));

        subtitulo1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitulo1.setText("Valor de abertura");
        fundoAbertura.add(subtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
        );

        fundoAbertura.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fundo.add(fundoAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 225, 106));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitulo2.setText("Valor que entrou");
        jPanel3.add(subtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 140, -1));

        valorEntrada.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        valorEntrada.setText("R$10.009,00");
        jPanel3.add(valorEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 64));

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fundo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 225, 106));

        logs.setColumns(20);
        logs.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        logs.setRows(5);
        logs.setBorder(null);
        logs.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(logs);

        fundo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 355, 290));

        titulocaixa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulocaixa.setText("Caixa atual");
        fundo.add(titulocaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, 43));

        btnFechar.setBackground(new java.awt.Color(255, 102, 102));
        btnFechar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addActionListener(this::btnFecharActionPerformed);
        fundo.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 459, 114, 45));

        btnAbrir.setBackground(new java.awt.Color(102, 255, 102));
        btnAbrir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbrir.addActionListener(this::btnAbrirActionPerformed);
        fundo.add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 459, 114, 45));

        logsDoCaixa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        logsDoCaixa.setText("Logs do Caixa");
        fundo.add(logsDoCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        fundoDados.setBackground(new java.awt.Color(253, 238, 239));
        fundoDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        topicos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos.setText("Data:");

        txtdata.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtdata.setText("jLabel1");

        topicos1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos1.setText("Hora:");

        txthora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txthora.setText("jLabel1");

        topicos2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos2.setText("Usuario:");

        txtuser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtuser.setText("jLabel1");

        topicos3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos3.setText("Valor Sangria:");

        txtsangria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtsangria.setText("jLabel1");

        btnSangria.setBackground(new java.awt.Color(255, 204, 204));
        btnSangria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSangria.setText("Sangria");
        btnSangria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSangria.addActionListener(this::btnSangriaActionPerformed);

        javax.swing.GroupLayout fundoDadosLayout = new javax.swing.GroupLayout(fundoDados);
        fundoDados.setLayout(fundoDadosLayout);
        fundoDadosLayout.setHorizontalGroup(
                fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fundoDadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(fundoDadosLayout.createSequentialGroup()
                                                .addComponent(topicos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(fundoDadosLayout.createSequentialGroup()
                                                .addComponent(topicos1)
                                                .addGap(6, 6, 6)
                                                .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(fundoDadosLayout.createSequentialGroup()
                                                .addComponent(topicos2)
                                                .addGap(6, 6, 6)
                                                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(fundoDadosLayout.createSequentialGroup()
                                                .addComponent(topicos3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(txtsangria, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnSangria))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fundoDadosLayout.setVerticalGroup(
                fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fundoDadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(topicos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(fundoDadosLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(txtdata)))
                                .addGap(6, 6, 6)
                                .addGroup(fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(topicos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(fundoDadosLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(txthora)))
                                .addGap(6, 6, 6)
                                .addGroup(fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(topicos2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(fundoDadosLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(txtuser)))
                                .addGap(6, 6, 6)
                                .addGroup(fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(topicos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(fundoDadosLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(txtsangria)))
                                .addGap(6, 6, 6)
                                .addComponent(btnSangria)
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        fundo.add(fundoDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, 190));

        menuLateral.setBackground(new java.awt.Color(251, 227, 228));

        NBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        NBLogo.setMaximumSize(new java.awt.Dimension(80, 80));
        NBLogo.setPreferredSize(new java.awt.Dimension(80, 80));

        menuLTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menuLTitulo.setText("NewBig-System");

        btnCaixa.setBackground(new java.awt.Color(253, 238, 239));
        btnCaixa.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.addActionListener(this::btnCaixaActionPerformed);

        btnFuncionarios.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnFuncionarios.setText("Funcionarios");
        btnFuncionarios.addActionListener(this::btnFuncionariosActionPerformed);

        btnClientes1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnClientes1.setText("Clientes");
        btnClientes1.addActionListener(this::btnClientes1ActionPerformed);

        btnLote.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnLote.setText("Lote");
        btnLote.addActionListener(this::btnLoteActionPerformed);

        btnProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnProduto.setText("Produtos");
        btnProduto.addActionListener(this::btnProdutoActionPerformed);

        btnVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnVenda.setText("Venda");
        btnVenda.addActionListener(this::btnVendaActionPerformed);

        btnInicio.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        LgNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LgNome.setText("Mourvan");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(40, 40));
        logo.setPreferredSize(new java.awt.Dimension(40, 40));

        LgAcesso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LgAcesso.setText("Administrador");

        javax.swing.GroupLayout menuLateralLayout = new javax.swing.GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
                menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(menuLTitulo)
                                .addGap(47, 47, 47))
                        .addGroup(menuLateralLayout.createSequentialGroup()
                                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(menuLateralLayout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addComponent(NBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(menuLateralLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(menuLateralLayout.createSequentialGroup()
                                                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(LgAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(LgNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnFuncionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnCaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnClientes1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnLote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(26, Short.MAX_VALUE))
        );
        menuLateralLayout.setVerticalGroup(
                menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuLTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLote, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(menuLateralLayout.createSequentialGroup()
                                                .addComponent(LgNome)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LgAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(9, 9, 9))
        );

        menuBar.setText("Menu");

        menuLogin.setText("Login");
        menuLogin.addActionListener(this::menuLoginActionPerformed);
        menuBar.add(menuLogin);

        menuSair.setText("Sair");
        menuSair.addActionListener(this::menuSairActionPerformed);
        menuBar.add(menuSair);

        MenuBarra.add(menuBar);

        setJMenuBar(MenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(menuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        TelaCaixa telaCaixa = new TelaCaixa(this.helpService, this.batchController, this.helpController);
        dispose();
        telaCaixa.setVisible(true);
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        TelaFuncionario telaFuncionario = new TelaFuncionario(this.helpService, this.batchController, this.helpController);
        dispose();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientes1ActionPerformed
        TelaCliente telaCliente = new TelaCliente(this.helpService, this.batchController, this.helpController);
        dispose();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_btnClientes1ActionPerformed

    private void btnLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoteActionPerformed
        ArrivalBatchView arrivalBatchView = new ArrivalBatchView(this.helpService, this.batchController, this.helpController);
        dispose();
        arrivalBatchView.setVisible(true);
    }//GEN-LAST:event_btnLoteActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        ProductView productView = new ProductView(this.helpService, this.batchController, this.helpController);
        dispose();
        productView.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        SalesView salesView = new SalesView(this.helpService, this.batchController, this.helpController);
        dispose();
        salesView.setVisible(true);
    }//GEN-LAST:event_btnVendaActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        TelaInicio tela = new TelaInicio(this.helpService, this.batchController, this.helpController);
        dispose();
        tela.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnSangriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSangriaActionPerformed
        if(caixa.verificarAbertura() == null){
            JOptionPane.showMessageDialog(
                    this,
                    "Não há caixa aberto!!!"
            );
        }
        else if(login.acessoNivel() != 1){
            JOptionPane.showMessageDialog(
                    this,
                    "Funcionario sem acesso para sangria!!"
            );
        }
        else{
            JSpinner input = new JSpinner(new SpinnerNumberModel(0.0, 0.0, 10000.0, 0.50));

            int opcao = JOptionPane.showConfirmDialog(
                    null,
                    input,
                    "Digite o valor de Sangria",
                    JOptionPane.OK_CANCEL_OPTION
            );

            if (opcao == JOptionPane.OK_OPTION) {
                double valor = (double) input.getValue();
                caixa.sangria(valor);
                JOptionPane.showMessageDialog(
                        this,
                        "Sangria de R$" + valor + "Concluida!!!"
                );
                preencherValores();
            }
        }
    }//GEN-LAST:event_btnSangriaActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        JSpinner input = new JSpinner(new SpinnerNumberModel(0.0, 0.0, 10000.0, 0.50));

        int opcao = JOptionPane.showConfirmDialog(
                null,
                input,
                "Digite o valor de abertura",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (opcao == JOptionPane.OK_OPTION) {
            double valor = (double) input.getValue();
            caixa.abrirCaixa(dadosUsuario.dadosCompletosFuncionario(login.consultarFun()), valor);
            preencherValores();
            preencherLog();
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        if(caixa.verificarAbertura() == null){
            JOptionPane.showMessageDialog(
                    this,
                    "Não há caixa aberto!!!"
            );
        }
        else{
            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja mesmo fechar o caixa?"
            );
            if(resposta == JOptionPane.YES_OPTION){
                caixa.fechar(dadosUsuario.dadosCompletosFuncionario(login.consultarFun()));
                preencherValores();
                preencherLog();
            }
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        Caixa caixa = new Caixa();
        TelaLogin telaLogin = new TelaLogin(this.helpService, this.batchController, this.helpController);
        if(caixa.verificarAbertura() != null){
            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Possui um caixa em aberto, deseja trocar de Login?"
            );
            if(resposta == JOptionPane.YES_OPTION){
                dispose();
                telaLogin.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(
                    this,
                    "Encerrado login!!!"
            );
            dispose();
            telaLogin.setVisible(true);
        }
    }//GEN-LAST:event_menuLoginActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        Caixa caixa = new Caixa();
        if(caixa.verificarAbertura() != null){
            JOptionPane.showMessageDialog(
                    this,
                    "Não é possivel encerrar o sistema!! Caixa está aberto"
            );
            TelaCaixa telaCaixa = new TelaCaixa(this.helpService, this.batchController, this.helpController);
            dispose();
            telaCaixa.setVisible(true);
        }
        else{
            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja mesmo encerrar o sistema?"
            );
            if(resposta == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }
    }//GEN-LAST:event_menuSairActionPerformed


    public void preencherValores(){
        try{
            valorAtual.setText("R$" + caixa.getValorAtual());
            valorAbertura.setText("R$" + caixa.getValorAbertura());
            valorEntrada.setText("R$" + (caixa.getValorAtual() - caixa.getValorAbertura()));
            var dados = caixa.getObjeto();
            txtuser.setText(dados.getUsuarioAbertura().getNome());
            txtdata.setText(dados.getDataAbertura().toString());
            txthora.setText(dados.getHoraAbertura().toString());
            txtsangria.setText("R$" + caixa.getSangria());
        }catch (Exception e){
            valorAtual.setText("R$" + 0.00);
            valorAbertura.setText("R$" + 0.00);
            valorEntrada.setText("R$" + 0.00);
            txtuser.setText("null");
            txtdata.setText("null");
            txthora.setText("null");
            txtsangria.setText("R$" + 0.0);
        }
    }

    public void preencherLog(){
        LogsDeCaixaService logsDeCaixaService = new LogsDeCaixaService();
        var lista = logsDeCaixaService.lista();
        logs.setEditable(false);
        logs.setText("");
        for (int i = 0; i < lista.size(); i++){
            logs.setText(lista.get(i).getDescricao()+ " | " + lista.get(i).getData() + "\n" + logs.getText());
        }
    }

    /*Funcões menu lateral*/

    public void logoUsuario(){
        ImageIcon icon = (ImageIcon) logo.getIcon();
        Image imagem = icon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        logo.setIcon(new ImageIcon(imagem));
    }

    public void logoNewBig(){
        ImageIcon icon = (ImageIcon) NBLogo.getIcon();
        Image imagem = icon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        NBLogo.setIcon(new ImageIcon(imagem));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCaixa(new HelpService(), new BatchControllerImpl(), new HelpController()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LgAcesso;
    private javax.swing.JLabel LgNome;
    private javax.swing.JMenuBar MenuBarra;
    private javax.swing.JLabel NBLogo;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnClientes1;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLote;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnSangria;
    private javax.swing.JButton btnVenda;
    private javax.swing.JPanel fundo;
    private javax.swing.JPanel fundoAbertura;
    private javax.swing.JPanel fundoDados;
    private javax.swing.JPanel fundoValorAtual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextArea logs;
    private javax.swing.JLabel logsDoCaixa;
    private javax.swing.JMenu menuBar;
    private javax.swing.JLabel menuLTitulo;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel subtitulo1;
    private javax.swing.JLabel subtitulo2;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulocaixa;
    private javax.swing.JLabel topicos;
    private javax.swing.JLabel topicos1;
    private javax.swing.JLabel topicos2;
    private javax.swing.JLabel topicos3;
    private javax.swing.JLabel txtdata;
    private javax.swing.JLabel txthora;
    private javax.swing.JLabel txtsangria;
    private javax.swing.JLabel txtuser;
    private javax.swing.JLabel valorAbertura;
    private javax.swing.JLabel valorAtual;
    private javax.swing.JLabel valorEntrada;
    // End of variables declaration//GEN-END:variables
}