/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view.sale;

import com.newBig.system.controller.HelpController;
import com.newBig.system.controller.batch.BatchControllerInterface;
import com.newBig.system.controller.batch.impl.BatchControllerImpl;
import com.newBig.system.controller.sale.dto.SaleSummaryDto;
import com.newBig.system.model.entity.Product;
import com.newBig.system.model.entity.SalesMovement;
import com.newBig.system.model.service.caixa.Caixa;
import com.newBig.system.model.service.HelpService;
import com.newBig.system.model.service.Login;
import com.newBig.system.view.caixa.TelaCaixa;
import com.newBig.system.view.funcionario.TelaFuncionario;
import com.newBig.system.view.inicio.TelaInicio;
import com.newBig.system.view.login.TelaLogin;
import com.newBig.system.view.batch.ArrivalBatchView;
import com.newBig.system.view.cliente.TelaCliente;
import com.newBig.system.view.product.ProductView;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.util.List;


/**
 *
 * @author bocchi
 */
public class SalesView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalesView.class.getName());
    Login login = new Login();
    private HelpService helpService;
    private final HelpController helpController;
    private Long currentSaleId = null;
    private Caixa caixa;
    //teste
    private final BatchControllerInterface batchController;

    /**
     * Creates new form SalesView
     */
    public SalesView(HelpService helpService, BatchControllerInterface batchController, HelpController helpController, Caixa caixa) {
        this.helpService = helpService;
        this.helpController = helpController;
        this.batchController = batchController;
        this.caixa = caixa;
        initComponents();

        logoUsuario();
        logoNewBig();
        LgNome.setText(login.nomeLog());
        LgAcesso.setText(login.acessoLog());

        loadSalesTable(0L);
        loadSaleInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLateral3 = new javax.swing.JPanel();
        NBLogo = new javax.swing.JLabel();
        menuLTitulo = new javax.swing.JLabel();
        btnCaixa = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        btnClientes1 = new javax.swing.JButton();
        btnLote = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        LgNome = new javax.swing.JLabel();
        LgAcesso = new javax.swing.JLabel();
        fundo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblSales = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        TxtSubtotal = new javax.swing.JLabel();
        TxtDisconto = new javax.swing.JLabel();
        TxtTaxa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TxtResultadoSubtotal = new javax.swing.JLabel();
        TxtResultadoDesconto = new javax.swing.JLabel();
        TxtResulTaxa = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TxtTotal = new javax.swing.JLabel();
        TxtResultadoTotal = new javax.swing.JLabel();
        btnFinalizarSale = new javax.swing.JButton();
        MenuBarra = new javax.swing.JMenuBar();
        menuBar = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuLateral3.setBackground(new java.awt.Color(251, 227, 228));

        NBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        NBLogo.setMaximumSize(new java.awt.Dimension(80, 80));
        NBLogo.setPreferredSize(new java.awt.Dimension(80, 80));

        menuLTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menuLTitulo.setText("NewBig-System");

        btnCaixa.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.addActionListener(this::btnCaixaActionPerformed);

        btnFuncionarios.setBackground(new java.awt.Color(253, 238, 239));
        btnFuncionarios.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnFuncionarios.setText("Funcionarios");
        btnFuncionarios.addActionListener(this::btnFuncionariosActionPerformed);

        btnClientes1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnClientes1.setText("Clientes");
        btnClientes1.addActionListener(this::btnClientes1ActionPerformed);

        btnLote.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnLote.setText("Lote");
        btnLote.addActionListener(this::btnLoteActionPerformed);

        btnProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnProduto.setText("Produtos");
        btnProduto.addActionListener(this::btnProdutoActionPerformed);

        btnVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnVenda.setText("Venda");
        btnVenda.addActionListener(this::btnVendaActionPerformed);

        btnInicio.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(40, 40));
        logo.setPreferredSize(new java.awt.Dimension(40, 40));

        LgNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LgNome.setText("Mourvan");

        LgAcesso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LgAcesso.setText("Administrador");

        javax.swing.GroupLayout menuLateral3Layout = new javax.swing.GroupLayout(menuLateral3);
        menuLateral3.setLayout(menuLateral3Layout);
        menuLateral3Layout.setHorizontalGroup(
            menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateral3Layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(menuLTitulo)
                .addGap(47, 47, 47))
            .addGroup(menuLateral3Layout.createSequentialGroup()
                .addGroup(menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLateral3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(NBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLateral3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLateral3Layout.createSequentialGroup()
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LgAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LgNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFuncionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClientes1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLateral3Layout.setVerticalGroup(
            menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateral3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLote, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLateral3Layout.createSequentialGroup()
                        .addComponent(LgNome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LgAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fundo.setBackground(new java.awt.Color(255, 249, 249));

        titulo.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        titulo.setText("Venda atual");

        TblSales.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        TblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Quantidade", "Preço unit.", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblSales);

        btnNovo.setBackground(new java.awt.Color(153, 255, 153));
        btnNovo.setText("Add item");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        btnDeletar.setBackground(new java.awt.Color(255, 102, 102));
        btnDeletar.setText("Deletar item");
        btnDeletar.addActionListener(this::btnDeletarActionPerformed);

        TxtSubtotal.setText("Subtotal:");

        TxtDisconto.setText("Desconto:");

        TxtTaxa.setText("Taxa:");

        TxtTotal.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        TxtTotal.setText("Total:");

        TxtResultadoTotal.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        TxtResultadoTotal.setForeground(new java.awt.Color(255, 102, 102));

        btnFinalizarSale.setBackground(new java.awt.Color(251, 227, 228));
        btnFinalizarSale.setForeground(new java.awt.Color(51, 51, 51));
        btnFinalizarSale.setText("Finalizar");
        btnFinalizarSale.addActionListener(this::btnFinalizarSaleActionPerformed);

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fundoLayout.createSequentialGroup()
                            .addComponent(TxtTotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtResultadoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(fundoLayout.createSequentialGroup()
                            .addComponent(btnFinalizarSale, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(fundoLayout.createSequentialGroup()
                            .addComponent(TxtDisconto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtResultadoDesconto))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(fundoLayout.createSequentialGroup()
                            .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtSubtotal)
                                .addComponent(TxtTaxa))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtResulTaxa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtResultadoSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizarSale, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtSubtotal)
                    .addComponent(TxtResultadoSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDisconto)
                    .addComponent(TxtResultadoDesconto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtTaxa)
                    .addComponent(TxtResulTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTotal)
                    .addComponent(TxtResultadoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        menuBar.setText("Menu");

        menuLogin.setText("Login");
        menuLogin.addActionListener(this::menuLoginActionPerformed);
        menuBar.add(menuLogin);

        menuSair.setText("Sair");
        menuSair.addActionListener(this::menuSairActionPerformed);
        menuBar.add(menuSair);

        MenuBarra.add(menuBar);

        setJMenuBar(MenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLateral3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLateral3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        Caixa caixa = new Caixa();
        TelaLogin telaLogin = new TelaLogin(this.helpService, this.batchController, this.helpController, this.caixa);
        if(caixa.verificarAbertura() != null){
            int resposta = JOptionPane.showConfirmDialog(
                this,
                "Possui um caixa em aberto, deseja trocar de Login?"
            );
            if(resposta == JOptionPane.YES_OPTION){
                dispose();
                telaLogin.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(
                this,
                "Encerrado login!!!"
            );
            dispose();
            telaLogin.setVisible(true);
        }
    }//GEN-LAST:event_menuLoginActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        Caixa caixa = new Caixa();
        if(caixa.verificarAbertura() != null){
            JOptionPane.showMessageDialog(
                this,
                "Não é possivel encerrar o sistema!! Caixa está aberto"
            );
            TelaCaixa telaCaixa = new TelaCaixa(this.helpService, this.batchController, this.helpController, this.caixa);
            dispose();
            telaCaixa.setVisible(true);
        }
        else{
            int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja mesmo encerrar o sistema?"
            );
            if(resposta == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }
    }//GEN-LAST:event_menuSairActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        TelaCaixa telaCaixa = new TelaCaixa(this.helpService, this.batchController, this.helpController, this.caixa);
        dispose();
        telaCaixa.setVisible(true);
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        TelaFuncionario telaFuncionario = new TelaFuncionario(this.helpService, this.batchController, this.helpController, this.caixa);
        dispose();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientes1ActionPerformed
        TelaCliente telaCliente = new TelaCliente(this.helpService, this.batchController, this.helpController, this.caixa);
        dispose();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_btnClientes1ActionPerformed

    private void btnLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoteActionPerformed

        ArrivalBatchView arrivalBatchView = new ArrivalBatchView(helpService, this.batchController, this.helpController, this.caixa);
        dispose();
        arrivalBatchView.setVisible(true);
    }//GEN-LAST:event_btnLoteActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        ProductView productView = new ProductView(this.helpService, this.batchController, this.helpController, this.caixa);
        dispose();
        productView.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        SalesView salesView = new SalesView(this.helpService, this.batchController, this.helpController, this.caixa);
        dispose();
        salesView.setVisible(true);
    }//GEN-LAST:event_btnVendaActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        TelaInicio tela = new TelaInicio(this.helpService, this.batchController, this.helpController, this.caixa);
        dispose();
        tela.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed


    private void loadSaleInformation() {
        DefaultTableModel tableModel = (DefaultTableModel) TblSales.getModel();
        BigDecimal subtotalAcumulado = BigDecimal.ZERO;

        //  = Percorre todas as linhas que estão atualmente na tabela
        for (int i = 0; i < tableModel.getRowCount(); i++) {

            Object valorColuna = tableModel.getValueAt(i, 4);

            if (valorColuna instanceof BigDecimal) {
                subtotalAcumulado = subtotalAcumulado.add((BigDecimal) valorColuna);
            } else if (valorColuna != null) {
                //  = Caso por algum motivo o valor venha como String ou Double, faz a conversão segura
                try {
                    subtotalAcumulado = subtotalAcumulado.add(new BigDecimal(valorColuna.toString()));
                } catch (NumberFormatException e) {
                    logger.warning("Não foi possível converter o valor da linha " + i + " para somar.");
                }
            }
        }

        //  = Aplica as regras de negócio básicas (Desconto e Taxa)
        BigDecimal desconto = BigDecimal.ZERO;
        BigDecimal taxa = BigDecimal.ZERO;

        //  = Total = Subtotal - Desconto + Taxa
        BigDecimal totalFinal = subtotalAcumulado.subtract(desconto).add(taxa);

        //  = Atualiza os componentes visuais
        TxtResultadoSubtotal.setText(String.format("R$ %.2f", subtotalAcumulado));
        TxtResultadoDesconto.setText(String.format("R$ %.2f", desconto));
        TxtResulTaxa.setText(String.format("R$ %.2f", taxa));
        TxtResultadoTotal.setText(String.format("R$ %.2f", totalFinal));
    }

    private void loadSalesTable(Long idSale) {

        DefaultTableModel tableModel = (DefaultTableModel) TblSales.getModel();
        tableModel.setNumRows(0);

        try {

            List<SaleSummaryDto> listDto = helpController.getSaleController().listSale(idSale);

            for (SaleSummaryDto s : listDto) {

                //  = Criamos variáveis seguras com valores padrão
                String nomeProduto = "Sem Produto";
                BigDecimal precoUnitario = BigDecimal.ZERO;
                int quantidade = 0;
                BigDecimal valorTotal = BigDecimal.ZERO;

                //  = Validações
                if (s.id() != null) {
                    quantidade = s.quantityItens();

                    if (s.idBatch() != null && s.nameProduct() != null) {

                        nomeProduto = s.nameProduct();
                        precoUnitario = s.unitPrice();

                        valorTotal = precoUnitario.multiply(BigDecimal.valueOf(quantidade));
                    }
                }

                tableModel.addRow(new Object[] {
                        s.id(),
                        nomeProduto,
                        quantidade,
                        precoUnitario,
                        valorTotal
                });

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
        }
    }

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {

        if (caixa.verificarAbertura() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Caixa ainda não foi aberto!!!"
            );
            return;
        }

        //  = Primeira lógica da venda, se não tiver uma venda inicializada vai criar a primeira e retornar o id dela
        if (this.currentSaleId == null) {
            this.currentSaleId = helpController.getSaleController().openSale();
        }

        FormSalesDialog formSalesDialog = new FormSalesDialog(this, true, this.helpService, this.currentSaleId, this.helpController);
        formSalesDialog.setLocationRelativeTo(this);
        formSalesDialog.setVisible(true);

        //  = Atualizamos a tabela sempe como o id da venda para pegar o itens dessa venda
        loadSalesTable(this.currentSaleId);
        loadSaleInformation();
    }                                       

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnFinalizarSaleActionPerformed(java.awt.event.ActionEvent evt) {
        // Verifica se existe uma venda aberta
        if (this.currentSaleId == null) {
            JOptionPane.showMessageDialog(this, "Nenhuma venda iniciada para finalizar!");
            return;
        }

        // Chama o Dialog de Pagamento passando o service e o ID
        FormSalePayDialog payDialog = new FormSalePayDialog(this, true, this.helpService, this.currentSaleId, this.helpController, this.caixa);
        payDialog.setLocationRelativeTo(this);
        payDialog.setVisible(true);

        // Após o dialog fechar, você pode resetar a tela para uma nova venda
        this.currentSaleId = null;
        loadSalesTable(0L);
        loadSaleInformation();
    }

    /*Funcões menu lateral*/

    public void logoUsuario(){
        ImageIcon icon = (ImageIcon) logo.getIcon();
        Image imagem = icon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        logo.setIcon(new ImageIcon(imagem));
    }

    public void logoNewBig(){
        ImageIcon icon = (ImageIcon) NBLogo.getIcon();
        Image imagem = icon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        NBLogo.setIcon(new ImageIcon(imagem));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        ////<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalesView(new HelpService(), new BatchControllerImpl(), new HelpController(), new Caixa()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LgAcesso;
    private javax.swing.JLabel LgNome;
    private javax.swing.JMenuBar MenuBarra;
    private javax.swing.JLabel NBLogo;
    private javax.swing.JTable TblSales;
    private javax.swing.JLabel TxtDisconto;
    private javax.swing.JLabel TxtResulTaxa;
    private javax.swing.JLabel TxtResultadoDesconto;
    private javax.swing.JLabel TxtResultadoSubtotal;
    private javax.swing.JLabel TxtResultadoTotal;
    private javax.swing.JLabel TxtSubtotal;
    private javax.swing.JLabel TxtTaxa;
    private javax.swing.JLabel TxtTotal;
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnClientes1;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnFinalizarSale;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLote;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnVenda;
    private javax.swing.JPanel fundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JMenu menuBar;
    private javax.swing.JLabel menuLTitulo;
    private javax.swing.JPanel menuLateral3;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
