/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.newBig.system.view;

import com.newBig.system.model.Sale;
import com.newBig.system.service.HelpService;

import javax.swing.*;
import java.math.BigDecimal;


/**
 *
 * @author bocchi
 */
public class FormSalePayDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSalePayDialog.class.getName());
    private HelpService helpService;
    private Long saleId;

    /**
     * Creates new form FormSaleDialog
     */
    public FormSalePayDialog(java.awt.Frame parent, boolean modal, HelpService helpService, Long saleId) {
        super(parent, modal);
        this.helpService = helpService;
        this.saleId = saleId;
        initComponents();
        configurarAcoesDosBotoes();
        esconderOpcoes();
    }

    // Método para esconder tudo ao iniciar
    private void esconderOpcoes() {
        rbCredito.setVisible(false);
        rbDebito.setVisible(false);
        lblChavePix.setVisible(false);
        txtValorRecebido.setVisible(false);
        // Supondo que você tenha um label do lado do txtValorRecebido
        // lblValorRecebidoText.setVisible(false);
    }

    // Configura o que aparece quando você clica em Pix, Cartão ou Dinheiro
    private void configurarAcoesDosBotoes() {
        rbCartao.addActionListener(e -> {
            esconderOpcoes();
            rbCredito.setVisible(true);
            rbDebito.setVisible(true);
        });

        rbPix.addActionListener(e -> {
            esconderOpcoes();
            lblChavePix.setVisible(true);
        });

        rbDinheiro.addActionListener(e -> {
            esconderOpcoes();
            txtValorRecebido.setVisible(true);
            // lblValorRecebidoText.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPagamento = new javax.swing.ButtonGroup();
        btnCartao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        divisa = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        rbCartao = new javax.swing.JRadioButton();
        rbPix = new javax.swing.JRadioButton();
        rbDinheiro = new javax.swing.JRadioButton();
        rbDebito = new javax.swing.JRadioButton();
        rbCredito = new javax.swing.JRadioButton();
        lblChavePix = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtValorRecebido = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 249, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        divisa.setBackground(new java.awt.Color(251, 227, 228));

        Titulo.setFont(new java.awt.Font("Unispace", 1, 20)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("PAGAMENTO");

        javax.swing.GroupLayout divisaLayout = new javax.swing.GroupLayout(divisa);
        divisa.setLayout(divisaLayout);
        divisaLayout.setHorizontalGroup(
            divisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divisaLayout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(334, 334, 334))
        );
        divisaLayout.setVerticalGroup(
            divisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(divisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 60));

        btnEnviar.setBackground(new java.awt.Color(153, 255, 153));
        btnEnviar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        btnEnviar.setText("Finalizar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 120, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 120, 40));

        btnPagamento.add(rbCartao);
        rbCartao.setText("CARTÃO");
        rbCartao.addActionListener(this::rbCartaoActionPerformed);
        jPanel1.add(rbCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 40));

        btnPagamento.add(rbPix);
        rbPix.setText("PIX");
        rbPix.addActionListener(this::rbPixActionPerformed);
        jPanel1.add(rbPix, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        btnPagamento.add(rbDinheiro);
        rbDinheiro.setText("DINHEIRO");
        rbDinheiro.addActionListener(this::rbDinheiroActionPerformed);
        jPanel1.add(rbDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        btnCartao.add(rbDebito);
        rbDebito.setText("Débito");
        jPanel1.add(rbDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        btnCartao.add(rbCredito);
        rbCredito.setText("Credito");
        rbCredito.addActionListener(this::rbCreditoActionPerformed);
        jPanel1.add(rbCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lblChavePix.setText("Chave PIX: 12.345.678/0001-90");
        jPanel1.add(lblChavePix, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel1.setText("Valor recebido:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));
        jPanel1.add(txtValorRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 160, -1));

        lblStatus.setText("Status: Aguardando Pagamento");
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String metodoPagamento = "";

            // Valida qual método foi escolhido
            if (rbCartao.isSelected()) {
                if (rbCredito.isSelected()) metodoPagamento = "CARTAO_CREDITO";
                else if (rbDebito.isSelected()) metodoPagamento = "CARTAO_DEBITO";
                else throw new Exception("Selecione se o cartão é Crédito ou Débito!");
            }
            else if (rbPix.isSelected()) {
                metodoPagamento = "PIX";
            }
            else if (rbDinheiro.isSelected()) {
                metodoPagamento = "DINHEIRO";
                String valorStr = txtValorRecebido.getText().replace(",", ".");
                if (valorStr.isEmpty()) throw new Exception("Informe o valor recebido em dinheiro!");

                BigDecimal valorRecebido = new BigDecimal(valorStr);
            }
            else {
                throw new Exception("Selecione uma forma de pagamento!");
            }

            // Atualiza o status visualmente
            lblStatus.setText("Status: FINALIZADO");
            lblStatus.setForeground(new java.awt.Color(0, 153, 51)); // Verde

            Sale newSale = helpService.getSaleService().findById(saleId);
            newSale.setPaymentMethod(metodoPagamento);
            newSale.setStatus("PAGO");
            helpService.getSaleService().editSale(newSale);

            JOptionPane.showMessageDialog(this, "Pagamento confirmado e venda finalizada com sucesso!");
            dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor numérico válido para o dinheiro.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Atenção: " + e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }


    private void rbCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCartaoActionPerformed

    private void rbPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPixActionPerformed

    private void rbDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDinheiroActionPerformed

    private void rbCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCreditoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormSalePayDialog dialog = new FormSalePayDialog(new javax.swing.JFrame(), true, new HelpService(), 0L);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnCartao;
    private javax.swing.JButton btnEnviar;
    private javax.swing.ButtonGroup btnPagamento;
    private javax.swing.JPanel divisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChavePix;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton rbCartao;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbDebito;
    private javax.swing.JRadioButton rbDinheiro;
    private javax.swing.JRadioButton rbPix;
    private javax.swing.JTextField txtValorRecebido;
    // End of variables declaration//GEN-END:variables
}
