/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view;

import com.newBig.system.service.CadastroUsuario;

import javax.swing.*;

/**
 *
 * @author MH
 */
public class TelaFormularioCliente extends JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaFormularioCliente.class.getName());
    CadastroUsuario cadastroUsuario = new CadastroUsuario();
    /**
     * Creates new form TelaFormularioCliente
     */
    public TelaFormularioCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        Long id = cadastroUsuario.ultimoId();
        txtId.setText(String.valueOf(id + 1));
        txtId.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        lblNome = new JLabel();
        txtNome = new JTextField();
        txtCpf = new JTextField();
        lblCpf = new JLabel();
        txtCep = new JTextField();
        lblCep = new JLabel();
        divisa = new JPanel();
        Titulo = new JLabel();
        btnEnviar = new JButton();
        btnCancelar = new JButton();
        lblNumero = new JLabel();
        lblBairro = new JLabel();
        txtBairro = new JTextField();
        lblTelefone = new JLabel();
        txtTelefone = new JTextField();
        lblRua = new JLabel();
        txtRua = new JTextField();
        spiNumero = new JSpinner();
        lblId = new JLabel();
        txtId = new JTextField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario-Clientes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 30));
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 260, 30));

        lblCpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCpf.setText("CPF");
        jPanel1.add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));
        jPanel1.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 260, 30));

        lblCep.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCep.setText("Cep");
        jPanel1.add(lblCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        divisa.setBackground(new java.awt.Color(248, 174, 176));
        divisa.setBorder(BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Titulo.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        Titulo.setText("Formulario Clientes");

        GroupLayout divisaLayout = new GroupLayout(divisa);
        divisa.setLayout(divisaLayout);
        divisaLayout.setHorizontalGroup(
            divisaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, divisaLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(283, 283, 283))
        );
        divisaLayout.setVerticalGroup(
            divisaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(divisaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Titulo)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(divisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 70));

        btnEnviar.setBackground(new java.awt.Color(153, 255, 153));
        btnEnviar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 120, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 120, 40));

        lblNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNumero.setText("Numero");
        jPanel1.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        lblBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblBairro.setText("Bairro");
        jPanel1.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 260, 30));

        lblTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTelefone.setText("Telefone");
        jPanel1.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 260, 30));

        lblRua.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRua.setText("Rua");
        jPanel1.add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));
        jPanel1.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 260, 30));
        jPanel1.add(spiNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 260, 30));

        lblId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblId.setText("ID");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        txtId.setActionCommand("<Not Set>");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 260, 30));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dispose();
    }

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try{
            String nome = txtNome.getText();
            String cpf = txtCpf.getText();
            String cep = txtCep.getText();
            String rua = txtRua.getText();
            int numero = (int) spiNumero.getValue();
            String bairro = txtBairro.getText();
            String telefone = txtTelefone.getText();
            if(nome.isEmpty() || cpf.isEmpty() || cep.isEmpty() || rua.isEmpty() || numero <= 0|| bairro.isEmpty() || telefone.isEmpty()){
                throw new Exception("Campo não preenchido!");
            }
            cadastroUsuario.novoCliente(nome,cpf,cep,rua,numero, bairro, telefone);
            JOptionPane.showMessageDialog(
                    this,
                    "Cliente cadastrado com sucesso!!"
            );
            dispose();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao cadastrar cliente confira os dados!!!! " + e.getMessage()
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaFormularioCliente().setVisible(false));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel Titulo;
    private JButton btnCancelar;
    private JButton btnEnviar;
    private JPanel divisa;
    private JPanel jPanel1;
    private JLabel lblBairro;
    private JLabel lblCep;
    private JLabel lblCpf;
    private JLabel lblId;
    private JLabel lblNome;
    private JLabel lblNumero;
    private JLabel lblRua;
    private JLabel lblTelefone;
    private JSpinner spiNumero;
    private JTextField txtBairro;
    private JTextField txtCep;
    private JTextField txtCpf;
    private JTextField txtId;
    private JTextField txtNome;
    private JTextField txtRua;
    private JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
