/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view;

import com.newBig.system.service.Caixa;
import com.newBig.system.service.OperacaoCaixa;

/**
 *
 * @author mourv
 */
public class TelaCaixa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCaixa.class.getName());
    Caixa caixa = new Caixa();
    /**
     * Creates new form TelaCaixa
     */
    public TelaCaixa() {
        initComponents();
        preencherValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        fundoValorAtual = new javax.swing.JPanel();
        subtitulo = new javax.swing.JLabel();
        valorAtual = new javax.swing.JLabel();
        fundoAbertura = new javax.swing.JPanel();
        valorAbertura = new javax.swing.JLabel();
        subtitulo1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        subtitulo2 = new javax.swing.JLabel();
        valorEntrada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        titulocaixa = new javax.swing.JLabel();
        topicos = new javax.swing.JLabel();
        topicos1 = new javax.swing.JLabel();
        topicos2 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnAbrir1 = new javax.swing.JButton();
        topicos3 = new javax.swing.JLabel();
        txtdata = new javax.swing.JLabel();
        txthora = new javax.swing.JLabel();
        taxtuser = new javax.swing.JLabel();
        txtsangria = new javax.swing.JLabel();
        btnSangria = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fundo.setBackground(new java.awt.Color(255, 255, 255));
        fundo.setPreferredSize(new java.awt.Dimension(760, 498));
        fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titulo.setText("Caixa");
        fundo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, 78, 54));

        fundoValorAtual.setBackground(new java.awt.Color(102, 102, 255));
        fundoValorAtual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitulo.setText("Valor atual");
        fundoValorAtual.add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, -1));

        valorAtual.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        valorAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorAtual.setText("R$10.009,00");
        fundoValorAtual.add(valorAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 64));

        fundo.add(fundoValorAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 225, 106));

        fundoAbertura.setBackground(new java.awt.Color(255, 255, 51));
        fundoAbertura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorAbertura.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        valorAbertura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorAbertura.setText("R$10.009,00");
        fundoAbertura.add(valorAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, -1, 54));

        subtitulo1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitulo1.setText("Valor de abertura");
        fundoAbertura.add(subtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        fundo.add(fundoAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 225, 106));

        jPanel3.setBackground(new java.awt.Color(102, 255, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitulo2.setText("Valor que entrou");
        jPanel3.add(subtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 140, -1));

        valorEntrada.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        valorEntrada.setText("R$10.009,00");
        jPanel3.add(valorEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 64));

        fundo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 225, 106));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        fundo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 355, 305));

        titulocaixa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulocaixa.setText("Caixa atual:");
        fundo.add(titulocaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 199, 120, 43));

        topicos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos.setText("Data:");
        fundo.add(topicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 248, 48, 30));

        topicos1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos1.setText("Hora:");
        fundo.add(topicos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 284, -1, 30));

        topicos2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos2.setText("Usuario:");
        fundo.add(topicos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 320, -1, 30));

        btnFechar.setBackground(new java.awt.Color(255, 153, 153));
        btnFechar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(this::btnFecharActionPerformed);
        fundo.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 459, 114, 45));

        btnAbrir1.setBackground(new java.awt.Color(102, 255, 102));
        btnAbrir1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAbrir1.setText("Abrir");
        btnAbrir1.addActionListener(this::btnAbrir1ActionPerformed);
        fundo.add(btnAbrir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 459, 114, 45));

        topicos3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos3.setText("Valor Sangria:");
        fundo.add(topicos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 356, 134, 30));

        txtdata.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtdata.setText("jLabel1");
        fundo.add(txtdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 256, 272, -1));

        txthora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txthora.setText("jLabel1");
        fundo.add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 292, 272, -1));

        taxtuser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        taxtuser.setText("jLabel1");
        fundo.add(taxtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 328, 244, -1));

        txtsangria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtsangria.setText("jLabel1");
        fundo.add(txtsangria, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 364, 186, -1));

        btnSangria.setBackground(new java.awt.Color(255, 204, 204));
        btnSangria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSangria.setText("Sangria");
        fundo.add(btnSangria, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 392, -1, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 180, Short.MAX_VALUE)
                .addComponent(fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnAbrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrir1ActionPerformed


    public void preencherValores(){
        valorAtual.setText("R$" + caixa.getValorAtual());
        valorAbertura.setText("R$" + caixa.getValorAbertura());
        valorEntrada.setText("R$" + (caixa.getValorAtual() - caixa.getValorAbertura()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCaixa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir1;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSangria;
    private javax.swing.JPanel fundo;
    private javax.swing.JPanel fundoAbertura;
    private javax.swing.JPanel fundoValorAtual;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel subtitulo1;
    private javax.swing.JLabel subtitulo2;
    private javax.swing.JLabel taxtuser;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulocaixa;
    private javax.swing.JLabel topicos;
    private javax.swing.JLabel topicos1;
    private javax.swing.JLabel topicos2;
    private javax.swing.JLabel topicos3;
    private javax.swing.JLabel txtdata;
    private javax.swing.JLabel txthora;
    private javax.swing.JLabel txtsangria;
    private javax.swing.JLabel valorAbertura;
    private javax.swing.JLabel valorAtual;
    private javax.swing.JLabel valorEntrada;
    // End of variables declaration//GEN-END:variables
}
