/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view;

import com.newBig.system.service.Login;

import javax.swing.*;

/**
 *
 * @author MH
 */
public class TelaLogin extends JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());
    Login loginService = new Login();
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        fundoLogin = new JPanel();
        subtitulo = new JLabel();
        lLogin = new JLabel();
        tLogin = new JTextField();
        lSenha = new JLabel();
        tSenha = new JPasswordField();
        titulo = new JLabel();
        btnEntrar = new JButton();
        nome = new JLabel();
        fundoEsquerda = new JPanel();
        logo = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("NewBig\n");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new java.awt.BorderLayout());

        fundoLogin.setBackground(new java.awt.Color(255, 255, 255));
        fundoLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo.setBackground(new java.awt.Color(0, 0, 0));
        subtitulo.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        subtitulo.setText("Login");
        fundoLogin.add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 104, -1, -1));

        lLogin.setFont(new java.awt.Font("Unispace", 0, 10)); // NOI18N
        lLogin.setText("Login");
        fundoLogin.add(lLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 145, -1, -1));

        tLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tLogin.setText("Login");
        fundoLogin.add(tLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 164, 219, 33));

        lSenha.setFont(new java.awt.Font("Unispace", 0, 10)); // NOI18N
        lSenha.setText("Senha");
        fundoLogin.add(lSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 215, -1, -1));

        tSenha.setText("1234");
        fundoLogin.add(tSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 234, 219, 33));

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        titulo.setText("NewBig Sorvetes");
        fundoLogin.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 63, 219, -1));

        btnEntrar.setBackground(new java.awt.Color(248, 174, 176));
        btnEntrar.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(null);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);
        fundoLogin.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 300, 219, 33));

        nome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nome.setForeground(new java.awt.Color(197, 197, 197));
        nome.setText("@NewBig-Sorvetes-e-Açai");
        fundoLogin.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        fundoEsquerda.setBackground(new java.awt.Color(248, 174, 176));

        logo.setIcon(new ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        GroupLayout fundoEsquerdaLayout = new GroupLayout(fundoEsquerda);
        fundoEsquerda.setLayout(fundoEsquerdaLayout);
        fundoEsquerdaLayout.setHorizontalGroup(
            fundoEsquerdaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(fundoEsquerdaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logo)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        fundoEsquerdaLayout.setVerticalGroup(
            fundoEsquerdaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(fundoEsquerdaLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(logo)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fundoEsquerda, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundoLogin, GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(fundoLogin, GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(fundoEsquerda, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {
        String vLogin = tLogin.getText(); /*Guarda o login*/
        int vSenha = Integer.parseInt(tSenha.getText()); /*Guarda a senha*/
        Long id = loginService.verificar(vLogin, vSenha);
        if(id == -1L){
            JOptionPane.showMessageDialog(
                    this,
                    "Funcionario não encontrado!!"
            );
        }
        else{
            int funAcesso = loginService.acesso(id);
            if(funAcesso > 2){
                JOptionPane.showMessageDialog(
                        this,
                        "Funcionario sem acesso!!"
                );
            }
            else{
                loginService.salvar(id);
                dispose();
                /*Entra no sistema*/
                /*teste na tela cliente deve ir para tela de abertura do sistema*/
                TelaCliente telaCliente = new TelaCliente();
                telaCliente.setVisible(true);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnEntrar;
    private JPanel fundoEsquerda;
    private JPanel fundoLogin;
    private JPanel jPanel1;
    private JLabel lLogin;
    private JLabel lSenha;
    private JLabel logo;
    private JLabel nome;
    private JLabel subtitulo;
    private JTextField tLogin;
    private JPasswordField tSenha;
    private JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
