/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view;

import com.newBig.system.service.AtualizarUsuario;
import com.newBig.system.service.CadastroUsuario;

import javax.swing.*;

/**
 *
 * @author MH
 */
public class TelaClientesAtualizar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaClientesAtualizar.class.getName());
    AtualizarUsuario atualizarUsuario = new AtualizarUsuario();
    /**
     * Creates new form TelaClientesAtualizar
     */
    public TelaClientesAtualizar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        divisa = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNumero = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        spiNumero = new javax.swing.JSpinner();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar-Clientes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 30));
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 260, 30));

        lblCpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCpf.setText("CPF");
        jPanel1.add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));
        jPanel1.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 260, 30));

        lblCep.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCep.setText("Cep");
        jPanel1.add(lblCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        divisa.setBackground(new java.awt.Color(248, 174, 176));
        divisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Titulo.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        Titulo.setText("Atualizar Clientes");

        javax.swing.GroupLayout divisaLayout = new javax.swing.GroupLayout(divisa);
        divisa.setLayout(divisaLayout);
        divisaLayout.setHorizontalGroup(
            divisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divisaLayout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(283, 283, 283))
        );
        divisaLayout.setVerticalGroup(
            divisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Titulo)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(divisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 70));

        btnEnviar.setBackground(new java.awt.Color(153, 255, 153));
        btnEnviar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 120, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 120, 40));

        lblNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNumero.setText("Numero");
        jPanel1.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        lblBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblBairro.setText("Bairro");
        jPanel1.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 260, 30));

        lblTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTelefone.setText("Telefone");
        jPanel1.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 260, 30));

        lblRua.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRua.setText("Rua");
        jPanel1.add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));
        jPanel1.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 260, 30));
        jPanel1.add(spiNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 260, 30));

        lblId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblId.setText("ID");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        txtId.setActionCommand("<Not Set>");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        try{
            Long id = Long.parseLong(txtId.getText());
            String nome = txtNome.getText();
            String cpf = txtCpf.getText();
            String cep = txtCep.getText();
            String rua = txtRua.getText();
            int numero = (int) spiNumero.getValue();
            String bairro = txtBairro.getText();
            String telefone = txtTelefone.getText();
            if(nome.isEmpty() || cpf.isEmpty() || cep.isEmpty() || rua.isEmpty() || numero <= 0|| bairro.isEmpty() || telefone.isEmpty()){
                throw new Exception("Campo não preenchido!");
            }
            atualizarUsuario.cliente(id, nome,cpf,cep,rua,numero, bairro, telefone);
            JOptionPane.showMessageDialog(
                    this,
                    "Cliente Atualizado com sucesso!!"
            );
            dispose();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao atualizar cliente confira os dados!!!! " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void preencher(Long id){
        var dados = atualizarUsuario.dadosCliente(id);
        txtId.setText(dados.getId().toString());
        txtId.setEnabled(false);
        txtNome.setText(dados.getNome());
        txtCpf.setText(dados.getCpf());
        txtCep.setText(dados.getCep());
        txtRua.setText(dados.getRua());
        txtBairro.setText(dados.getBairro());
        txtTelefone.setText(dados.getTelefone());
        spiNumero.setValue(dados.getNumero());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaClientesAtualizar().setVisible(false));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JPanel divisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JSpinner spiNumero;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
