/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view;

import com.newBig.system.service.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author MH
 */
public class TelaFuncionario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaFuncionario.class.getName());
    TelaCadastroFuncionario telaCadastroFuncionario = new TelaCadastroFuncionario();
    TelaAtualizarFuncionarios telaAtualizarFuncionarios = new TelaAtualizarFuncionarios();
    Login login = new Login();
    private HelpService helpService;

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario(HelpService helpService) {
        this.helpService = helpService;
        initComponents();
        logoUsuario();
        logoNewBig();
        LgNome.setText(login.nomeLog());
        LgAcesso.setText(login.acessoLog());
        this.setLocationRelativeTo(null);
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFuncionarios = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        TxtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnDados = new javax.swing.JButton();
        menuLateral3 = new javax.swing.JPanel();
        NBLogo = new javax.swing.JLabel();
        menuLTitulo = new javax.swing.JLabel();
        btnCaixa = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        btnClientes1 = new javax.swing.JButton();
        btnLote = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        LgNome = new javax.swing.JLabel();
        LgAcesso = new javax.swing.JLabel();
        MenuBarra = new javax.swing.JMenuBar();
        menuBar = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("Funcionarios"); // NOI18N

        fundo.setBackground(new java.awt.Color(255, 249, 249));

        titulo.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        titulo.setText("Funcionarios");

        TabelaFuncionarios.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        TabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "ID", "Nome", "Acesso", "Login"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaFuncionarios);
        if (TabelaFuncionarios.getColumnModel().getColumnCount() > 0) {
            TabelaFuncionarios.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        btnNovo.setBackground(new java.awt.Color(153, 255, 153));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        btnAtualizar.setBackground(new java.awt.Color(255, 255, 153));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        btnDeletar.setBackground(new java.awt.Color(255, 102, 102));
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(this::btnDeletarActionPerformed);

        TxtBuscar.setToolTipText("");
        TxtBuscar.addActionListener(this::TxtBuscarActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnDados.setBackground(new java.awt.Color(51, 153, 255));
        btnDados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDados.setText("Dados Adicionais");
        btnDados.addActionListener(this::btnDadosActionPerformed);

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
                fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fundoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(fundoLayout.createSequentialGroup()
                                                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(fundoLayout.createSequentialGroup()
                                                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnBuscar))
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(47, Short.MAX_VALUE))
                                        .addGroup(fundoLayout.createSequentialGroup()
                                                .addComponent(btnNovo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAtualizar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnDeletar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnDados)
                                                .addGap(46, 46, 46))))
        );
        fundoLayout.setVerticalGroup(
                fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fundoLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(titulo)
                                        .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBuscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 12, Short.MAX_VALUE))
        );

        menuLateral3.setBackground(new java.awt.Color(251, 227, 228));

        NBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        NBLogo.setMaximumSize(new java.awt.Dimension(80, 80));
        NBLogo.setPreferredSize(new java.awt.Dimension(80, 80));

        menuLTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menuLTitulo.setText("NewBig-System");

        btnCaixa.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.addActionListener(this::btnCaixaActionPerformed);

        btnFuncionarios.setBackground(new java.awt.Color(253, 238, 239));
        btnFuncionarios.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnFuncionarios.setText("Funcionarios");
        btnFuncionarios.addActionListener(this::btnFuncionariosActionPerformed);

        btnClientes1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnClientes1.setText("Clientes");
        btnClientes1.addActionListener(this::btnClientes1ActionPerformed);

        btnLote.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnLote.setText("Lote");
        btnLote.addActionListener(this::btnLoteActionPerformed);

        btnProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnProduto.setText("Produtos");
        btnProduto.addActionListener(this::btnProdutoActionPerformed);

        btnVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnVenda.setText("Venda");
        btnVenda.addActionListener(this::btnVendaActionPerformed);

        btnInicio.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(40, 40));
        logo.setPreferredSize(new java.awt.Dimension(40, 40));

        LgNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LgNome.setText("Mourvan");

        LgAcesso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LgAcesso.setText("Administrador");

        javax.swing.GroupLayout menuLateral3Layout = new javax.swing.GroupLayout(menuLateral3);
        menuLateral3.setLayout(menuLateral3Layout);
        menuLateral3Layout.setHorizontalGroup(
                menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateral3Layout.createSequentialGroup()
                                .addGap(0, 53, Short.MAX_VALUE)
                                .addComponent(menuLTitulo)
                                .addGap(47, 47, 47))
                        .addGroup(menuLateral3Layout.createSequentialGroup()
                                .addGroup(menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(menuLateral3Layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addComponent(NBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(menuLateral3Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(menuLateral3Layout.createSequentialGroup()
                                                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(LgAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(LgNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnFuncionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnCaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnClientes1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnLote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLateral3Layout.setVerticalGroup(
                menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateral3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuLTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLote, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(menuLateral3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(menuLateral3Layout.createSequentialGroup()
                                                .addComponent(LgNome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LgAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        menuBar.setText("Menu");

        menuLogin.setText("Login");
        menuLogin.addActionListener(this::menuLoginActionPerformed);
        menuBar.add(menuLogin);

        menuSair.setText("Sair");
        menuSair.addActionListener(this::menuSairActionPerformed);
        menuBar.add(menuSair);

        MenuBarra.add(menuBar);

        setJMenuBar(MenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(menuLateral3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuLateral3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        if(login.acessoNivel() != 1){
            JOptionPane.showMessageDialog(
                    this,
                    "Funcionario sem acesso a esse serviço!!"
            );
        }
        else {
            telaCadastroFuncionario.setVisible(true);
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if(login.acessoNivel() != 1){
            JOptionPane.showMessageDialog(
                    this,
                    "Funcionario sem acesso a esse serviço!!"
            );
        }
        else{
            int linha = TabelaFuncionarios.getSelectedRow();
            if(linha == -1){
                JOptionPane.showMessageDialog(
                        this,
                        "Nenhum Funcionario selecionado!!"

                );
            }
            else{
                Long id = (Long) TabelaFuncionarios.getValueAt(linha, 0);
                telaAtualizarFuncionarios.preencher(id);
                telaAtualizarFuncionarios.setVisible(true);
                preencherTabela();
            }
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if(login.acessoNivel() != 1){
            JOptionPane.showMessageDialog(
                    this,
                    "Funcionario sem acesso a esse serviço!!"
            );
        }
        else {
            int linha = TabelaFuncionarios.getSelectedRow();
            Long id = (Long) TabelaFuncionarios.getValueAt(linha, 0);
            String nome = (String) TabelaFuncionarios.getValueAt(linha, 1);
            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja mesmo apagar o funcionario " + nome + "?"
            );
            if (resposta == JOptionPane.YES_OPTION) {
                DeletarUsuario deletarUsuario = new DeletarUsuario();
                deletarUsuario.deleteFuncionario(id);
                preencherTabela();

            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        preencherNome();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        if(login.acessoNivel() != 1){
            JOptionPane.showMessageDialog(
                    this,
                    "Funcionario sem acesso a esse serviço!!"
            );
        }
        else {
            DadosUsuario dadosUsuario = new DadosUsuario();
            int linha = TabelaFuncionarios.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(
                        this,
                        "Nenhum funcionario selecionado!!"

                );
            } else {
                Long id = (Long) TabelaFuncionarios.getValueAt(linha, 0);
                var lista = dadosUsuario.dadosCompletosFuncionario(id);
                JOptionPane.showMessageDialog(
                        this,
                        "ID: " + lista.getId() + "\n" +
                                "Nome: " + lista.getNome() + "\n" +
                                "Cpf: " + lista.getCpf() + "\n" +
                                "Login: " + lista.getLogin() + "\n" +
                                "Senha: " + lista.getSenha()

                );
            }
        }

    }//GEN-LAST:event_btnDadosActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        TelaCaixa telaCaixa = new TelaCaixa(this.helpService);
        dispose();
        telaCaixa.setVisible(true);
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        TelaFuncionario telaFuncionario = new TelaFuncionario(this.helpService);
        dispose();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientes1ActionPerformed
        TelaCliente telaCliente = new TelaCliente(this.helpService);
        dispose();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_btnClientes1ActionPerformed

    private void btnLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoteActionPerformed
        ArrivalBatchView arrivalBatchView = new ArrivalBatchView(this.helpService);
        dispose();
        arrivalBatchView.setVisible(true);
    }//GEN-LAST:event_btnLoteActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        ProductView productView = new ProductView(this.helpService);
        dispose();
        productView.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        SalesView salesView = new SalesView(this.helpService);
        dispose();
        salesView.setVisible(true);
    }//GEN-LAST:event_btnVendaActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        TelaInicio tela = new TelaInicio(this.helpService);
        dispose();
        tela.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        Caixa caixa = new Caixa();
        TelaLogin telaLogin = new TelaLogin(this.helpService);
        if(caixa.verificarAbertura() != null){
            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Possui um caixa em aberto, deseja trocar de Login?"
            );
            if(resposta == JOptionPane.YES_OPTION){
                dispose();
                telaLogin.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(
                    this,
                    "Encerrado login!!!"
            );
            dispose();
            telaLogin.setVisible(true);
        }
    }//GEN-LAST:event_menuLoginActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        Caixa caixa = new Caixa();
        if(caixa.verificarAbertura() != null){
            JOptionPane.showMessageDialog(
                    this,
                    "Não é possivel encerrar o sistema!! Caixa está aberto"
            );
            TelaCaixa telaCaixa = new TelaCaixa(this.helpService);
            dispose();
            telaCaixa.setVisible(true);
        }
        else{
            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja mesmo encerrar o sistema?"
            );
            if(resposta == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }
    }//GEN-LAST:event_menuSairActionPerformed


    public void preencherTabela(){
        DadosUsuario dadosUsuario = new DadosUsuario();
        DefaultTableModel linha = (DefaultTableModel) TabelaFuncionarios.getModel();
        linha.setRowCount(0);
        var lista = dadosUsuario.dadosFuncionario();
        for (int i = 0; i < lista.size() ; i++) {
            if(lista.get(i).getAcesso() == 1){ /*Verificar se é administrador*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Administrador",
                        lista.get(i).getLogin()
                });
            } else if (lista.get(i).getAcesso() == 2) { /*Verificar se é operador*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Operador",
                        lista.get(i).getLogin()
                });
            }
            else{ /*Se não é nada é sem acesso*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Sem Acesso",
                        lista.get(i).getLogin()
                });
            }

        }
    }

    public void preencherNome(){
        DadosUsuario dadosUsuario = new DadosUsuario();
        DefaultTableModel linha = (DefaultTableModel) TabelaFuncionarios.getModel();
        linha.setRowCount(0);
        String nome = TxtBuscar.getText();
        linha.setRowCount(0);
        var lista = dadosUsuario.dadosFuncionarioNome(nome);
        for (int i = 0; i < lista.size() ; i++) {
            if(lista.get(i).getAcesso() == 1){ /*Verificar se é administrador*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Administrador",
                        lista.get(i).getLogin()
                });
            } else if (lista.get(i).getAcesso() == 2) { /*Verificar se é operador*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Operador",
                        lista.get(i).getLogin()
                });
            }
            else{ /*Se não é nada é sem acesso*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Sem Acesso",
                        lista.get(i).getLogin()
                });
            }

        }
    }
    /*Funcões menu lateral*/

    public void logoUsuario(){
        ImageIcon icon = (ImageIcon) logo.getIcon();
        Image imagem = icon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        logo.setIcon(new ImageIcon(imagem));
    }

    public void logoNewBig(){
        ImageIcon icon = (ImageIcon) NBLogo.getIcon();
        Image imagem = icon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        NBLogo.setIcon(new ImageIcon(imagem));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaFuncionario(new HelpService()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LgAcesso;
    private javax.swing.JLabel LgNome;
    private javax.swing.JMenuBar MenuBarra;
    private javax.swing.JLabel NBLogo;
    private javax.swing.JTable TabelaFuncionarios;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnClientes1;
    private javax.swing.JButton btnDados;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLote;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnVenda;
    private javax.swing.JPanel fundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JMenu menuBar;
    private javax.swing.JLabel menuLTitulo;
    private javax.swing.JPanel menuLateral3;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}