/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view;

import com.newBig.system.repository.ClienteRepo;
import com.newBig.system.repository.CustomizerFactory;
import com.newBig.system.repository.FuncionarioRepo;
import jakarta.persistence.EntityManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MH
 */
public class TelaFuncionario extends JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaFuncionario.class.getName());
    TelaCadastroFuncionario telaCadastroFuncionario = new TelaCadastroFuncionario();
    TelaAtualizarFuncionarios telaAtualizarFuncionarios = new TelaAtualizarFuncionarios();
    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new JPanel();
        titulo = new JLabel();
        jScrollPane1 = new JScrollPane();
        TabelaFuncionarios = new JTable();
        btnNovo = new JButton();
        btnAtualizar = new JButton();
        btnDeletar = new JButton();
        TxtBuscar = new JTextField();
        btnBuscar = new JButton();
        btnDados = new JButton();
        menuLateral3 = new JPanel();
        Lgfundo3 = new JPanel();
        LgNome3 = new JLabel();
        LgAcesso3 = new JLabel();
        logo3 = new JLabel();
        NBLogo = new JLabel();
        menuLTitulo = new JLabel();
        btnClientes = new JButton();
        btnFuncionarios = new JButton();
        btnCaixa = new JButton();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        jMenu2 = new JMenu();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setName("Funcionarios"); // NOI18N

        fundo.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        titulo.setText("Funcionarios");

        TabelaFuncionarios.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        TabelaFuncionarios.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Acesso", "Login"
            }
        ) {
            Class[] types = new Class [] {
                Long.class, String.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaFuncionarios);
        if (TabelaFuncionarios.getColumnModel().getColumnCount() > 0) {
            TabelaFuncionarios.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        btnNovo.setBackground(new java.awt.Color(153, 255, 153));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        btnAtualizar.setBackground(new java.awt.Color(255, 255, 153));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        btnDeletar.setBackground(new java.awt.Color(255, 102, 102));
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(this::btnDeletarActionPerformed);

        TxtBuscar.setToolTipText("");
        TxtBuscar.addActionListener(this::TxtBuscarActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnDados.setBackground(new java.awt.Color(51, 153, 255));
        btnDados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDados.setText("Dados Adicionais");
        btnDados.addActionListener(this::btnDadosActionPerformed);

        GroupLayout fundoLayout = new GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(fundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addGroup(fundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(fundoLayout.createSequentialGroup()
                                .addComponent(titulo, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtBuscar, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 703, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeletar)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDados)
                        .addGap(46, 46, 46))))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(fundoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(TxtBuscar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btnDados, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovo, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAtualizar, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeletar, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        menuLateral3.setBackground(new java.awt.Color(248, 174, 176));

        Lgfundo3.setBackground(new java.awt.Color(204, 204, 204));
        Lgfundo3.setBorder(BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LgNome3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LgNome3.setText("Mourvan");

        LgAcesso3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LgAcesso3.setText("Administrador");

        logo3.setIcon(new ImageIcon(getClass().getResource("/images/avatar.png"))); // NOI18N
        logo3.setMaximumSize(new java.awt.Dimension(40, 40));
        logo3.setPreferredSize(new java.awt.Dimension(40, 40));

        GroupLayout Lgfundo3Layout = new GroupLayout(Lgfundo3);
        Lgfundo3.setLayout(Lgfundo3Layout);
        Lgfundo3Layout.setHorizontalGroup(
            Lgfundo3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, Lgfundo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo3, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Lgfundo3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(LgAcesso3, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                    .addComponent(LgNome3, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Lgfundo3Layout.setVerticalGroup(
            Lgfundo3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, Lgfundo3Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Lgfundo3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(logo3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(Lgfundo3Layout.createSequentialGroup()
                        .addComponent(LgNome3, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LgAcesso3, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        NBLogo.setIcon(new ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        NBLogo.setMaximumSize(new java.awt.Dimension(80, 80));
        NBLogo.setPreferredSize(new java.awt.Dimension(80, 80));

        menuLTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menuLTitulo.setText("NewBig-System");

        btnClientes.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnFuncionarios.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnFuncionarios.setText("Funcionarios");
        btnFuncionarios.addActionListener(this::btnFuncionariosActionPerformed);

        btnCaixa.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.addActionListener(this::btnCaixaActionPerformed);

        GroupLayout menuLateral3Layout = new GroupLayout(menuLateral3);
        menuLateral3.setLayout(menuLateral3Layout);
        menuLateral3Layout.setHorizontalGroup(
            menuLateral3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(menuLateral3Layout.createSequentialGroup()
                .addGroup(menuLateral3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(menuLateral3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lgfundo3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuLateral3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(NBLogo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(GroupLayout.Alignment.TRAILING, menuLateral3Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(menuLateral3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, menuLateral3Layout.createSequentialGroup()
                        .addComponent(menuLTitulo)
                        .addGap(47, 47, 47))
                    .addGroup(GroupLayout.Alignment.TRAILING, menuLateral3Layout.createSequentialGroup()
                        .addComponent(btnClientes, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(menuLateral3Layout.createSequentialGroup()
                        .addGroup(menuLateral3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(btnFuncionarios, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCaixa, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
        menuLateral3Layout.setVerticalGroup(
            menuLateral3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, menuLateral3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NBLogo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLTitulo)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClientes, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFuncionarios, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCaixa, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lgfundo3, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuLateral3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(fundo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuLateral3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
       telaCadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        int linha = TabelaFuncionarios.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(
                    this,
                    "Nenhum Funcionario selecionado!!"

            );
        }
        else{
            Long id = (Long) TabelaFuncionarios.getValueAt(linha, 0);
            telaAtualizarFuncionarios.preencher(id);
            telaAtualizarFuncionarios.setVisible(true);
            preencherTabela();
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        EntityManager em = CustomizerFactory.getEntityManager(); /*Pegar objeto que conecta com o banco*/
        FuncionarioRepo dados = new FuncionarioRepo(em);
        int linha = TabelaFuncionarios.getSelectedRow();
        Long id = (Long) TabelaFuncionarios.getValueAt(linha, 0);
        String nome = (String) TabelaFuncionarios.getValueAt(linha, 1);
        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja mesmo apagar o funcionario " + nome +"?"
        );
        if(resposta == JOptionPane.YES_OPTION){
            dados.delete(dados.SelecionarFuncionario(id));
            preencherTabela();

        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        preencherNome();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        EntityManager em = CustomizerFactory.getEntityManager(); /*Pegar objeto que conecta com o banco*/
        FuncionarioRepo dados = new FuncionarioRepo(em);
        int linha = TabelaFuncionarios.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(
                    this,
                    "Nenhum funcionario selecionado!!"

            );
        }
        else{
            Long id = (Long) TabelaFuncionarios.getValueAt(linha, 0);
            var lista = dados.SelecionarFuncionario(id);
            JOptionPane.showMessageDialog(
                    this,
                    "ID: " + lista.getId() + "\n" +
                            "Nome: " + lista.getNome()  + "\n" +
                            "Cpf: " + lista.getCpf() + "\n" +
                            "Login: " + lista.getLogin() + "\n" +
                            "Senha: " + lista.getSenha()

            );
        }

    }//GEN-LAST:event_btnDadosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        TelaCliente telaCliente = new TelaCliente();
        dispose();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        TelaFuncionario telaFuncionario = new TelaFuncionario();
        dispose();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        TelaCaixa telaCaixa = new TelaCaixa();
        dispose();
        telaCaixa.setVisible(true);
    }//GEN-LAST:event_btnCaixaActionPerformed


    public void preencherTabela(){
        EntityManager em = CustomizerFactory.getEntityManager(); /*Pegar objeto que conecta com o banco*/
        FuncionarioRepo dados = new FuncionarioRepo(em);
        DefaultTableModel linha = (DefaultTableModel) TabelaFuncionarios.getModel();
        linha.setRowCount(0);
        var lista = dados.BuscaFuncionarios();
        for (int i = 0; i < lista.size() ; i++) {
            if(lista.get(i).getAcesso() == 1){ /*Verificar se é administrador*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Administrador",
                        lista.get(i).getLogin()
                });
            } else if (lista.get(i).getAcesso() == 2) { /*Verificar se é operador*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Operador",
                        lista.get(i).getLogin()
                });
            }
            else{ /*Se não é nada é sem acesso*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Sem Acesso",
                        lista.get(i).getLogin()
                });
            }

        }
    }

    public void preencherNome(){
        EntityManager em = CustomizerFactory.getEntityManager(); /*Pegar objeto que conecta com o banco*/
        FuncionarioRepo dados = new FuncionarioRepo(em);
        DefaultTableModel linha = (DefaultTableModel) TabelaFuncionarios.getModel();
        linha.setRowCount(0);
        String nome = TxtBuscar.getText();
        linha.setRowCount(0);
        var lista = dados.BuscaPorNome(nome);
        for (int i = 0; i < lista.size() ; i++) {
            if(lista.get(i).getAcesso() == 1){ /*Verificar se é administrador*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Administrador",
                        lista.get(i).getLogin()
                });
            } else if (lista.get(i).getAcesso() == 2) { /*Verificar se é operador*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Operador",
                        lista.get(i).getLogin()
                });
            }
            else{ /*Se não é nada é sem acesso*/
                linha.addRow(new Object[]{
                        lista.get(i).getId(),
                        lista.get(i).getNome(),
                        "Sem Acesso",
                        lista.get(i).getLogin()
                });
            }

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaFuncionario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel LgAcesso;
    private JLabel LgAcesso1;
    private JLabel LgAcesso2;
    private JLabel LgAcesso3;
    private JLabel LgNome;
    private JLabel LgNome1;
    private JLabel LgNome2;
    private JLabel LgNome3;
    private JPanel Lgfundo;
    private JPanel Lgfundo1;
    private JPanel Lgfundo2;
    private JPanel Lgfundo3;
    private JLabel NBLogo;
    private JTable TabelaFuncionarios;
    private JTextField TxtBuscar;
    private JButton btnAtualizar;
    private JButton btnBuscar;
    private JButton btnCaixa;
    private JButton btnClientes;
    private JButton btnDados;
    private JButton btnDeletar;
    private JButton btnFuncionarios;
    private JButton btnNovo;
    private JPanel fundo;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenuBar jMenuBar1;
    private JScrollPane jScrollPane1;
    private JLabel logo;
    private JLabel logo1;
    private JLabel logo2;
    private JLabel logo3;
    private JLabel menuLTitulo;
    private JPanel menuLateral;
    private JPanel menuLateral1;
    private JPanel menuLateral2;
    private JPanel menuLateral3;
    private JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
