/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view;

import com.newBig.system.service.Caixa;
import com.newBig.system.service.DadosUsuario;
import com.newBig.system.service.LogsDeCaixaService;

import javax.swing.*;

/**
 *
 * @author mourv
 */
public class TelaCaixa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCaixa.class.getName());
    Caixa caixa = new Caixa();
    DadosUsuario dadosUsuario = new DadosUsuario();
    /**
     * Creates new form TelaCaixa
     */
    public TelaCaixa() {
        initComponents();
        this.setLocationRelativeTo(null);
        preencherValores();
        preencherLog();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        fundoValorAtual = new javax.swing.JPanel();
        subtitulo = new javax.swing.JLabel();
        valorAtual = new javax.swing.JLabel();
        fundoAbertura = new javax.swing.JPanel();
        valorAbertura = new javax.swing.JLabel();
        subtitulo1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        subtitulo2 = new javax.swing.JLabel();
        valorEntrada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logs = new javax.swing.JTextArea();
        titulocaixa = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        logsDoCaixa = new javax.swing.JLabel();
        fundoDados = new javax.swing.JPanel();
        topicos = new javax.swing.JLabel();
        txtdata = new javax.swing.JLabel();
        topicos1 = new javax.swing.JLabel();
        txthora = new javax.swing.JLabel();
        topicos2 = new javax.swing.JLabel();
        txtuser = new javax.swing.JLabel();
        topicos3 = new javax.swing.JLabel();
        txtsangria = new javax.swing.JLabel();
        btnSangria = new javax.swing.JButton();
        menuLateral = new javax.swing.JPanel();
        Lgfundo = new javax.swing.JPanel();
        LgNome = new javax.swing.JLabel();
        LgAcesso = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        NBLogo = new javax.swing.JLabel();
        menuLTitulo = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        btnCaixa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        fundo.setBackground(new java.awt.Color(255, 255, 255));
        fundo.setToolTipText("");
        fundo.setPreferredSize(new java.awt.Dimension(760, 498));
        fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titulo.setText("Caixa");
        fundo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, 78, 54));

        fundoValorAtual.setBackground(new java.awt.Color(102, 153, 255));
        fundoValorAtual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fundoValorAtual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitulo.setText("Valor atual");
        fundoValorAtual.add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, -1));

        valorAtual.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        valorAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorAtual.setText("R$10.009,00");
        fundoValorAtual.add(valorAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 64));

        fundo.add(fundoValorAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 225, 106));

        fundoAbertura.setBackground(new java.awt.Color(255, 255, 51));
        fundoAbertura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fundoAbertura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorAbertura.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        valorAbertura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorAbertura.setText("R$10.009,00");
        fundoAbertura.add(valorAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, -1, 54));

        subtitulo1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitulo1.setText("Valor de abertura");
        fundoAbertura.add(subtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        fundo.add(fundoAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 225, 106));

        jPanel3.setBackground(new java.awt.Color(102, 255, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitulo2.setText("Valor que entrou");
        jPanel3.add(subtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 140, -1));

        valorEntrada.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        valorEntrada.setText("R$10.009,00");
        jPanel3.add(valorEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 64));

        fundo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 225, 106));

        logs.setColumns(20);
        logs.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        logs.setRows(5);
        logs.setBorder(null);
        logs.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(logs);

        fundo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 355, 290));

        titulocaixa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulocaixa.setText("Caixa atual");
        fundo.add(titulocaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, 43));

        btnFechar.setBackground(new java.awt.Color(255, 102, 102));
        btnFechar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addActionListener(this::btnFecharActionPerformed);
        fundo.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 459, 114, 45));

        btnAbrir.setBackground(new java.awt.Color(102, 255, 102));
        btnAbrir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbrir.addActionListener(this::btnAbrirActionPerformed);
        fundo.add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 459, 114, 45));

        logsDoCaixa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        logsDoCaixa.setText("Logs do Caixa");
        fundo.add(logsDoCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        fundoDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        topicos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos.setText("Data:");

        txtdata.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtdata.setText("jLabel1");

        topicos1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos1.setText("Hora:");

        txthora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txthora.setText("jLabel1");

        topicos2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos2.setText("Usuario:");

        txtuser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtuser.setText("jLabel1");

        topicos3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topicos3.setText("Valor Sangria:");

        txtsangria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtsangria.setText("jLabel1");

        btnSangria.setBackground(new java.awt.Color(255, 204, 204));
        btnSangria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSangria.setText("Sangria");
        btnSangria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSangria.addActionListener(this::btnSangriaActionPerformed);

        javax.swing.GroupLayout fundoDadosLayout = new javax.swing.GroupLayout(fundoDados);
        fundoDados.setLayout(fundoDadosLayout);
        fundoDadosLayout.setHorizontalGroup(
            fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoDadosLayout.createSequentialGroup()
                        .addComponent(topicos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundoDadosLayout.createSequentialGroup()
                        .addComponent(topicos1)
                        .addGap(6, 6, 6)
                        .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundoDadosLayout.createSequentialGroup()
                        .addComponent(topicos2)
                        .addGap(6, 6, 6)
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundoDadosLayout.createSequentialGroup()
                        .addComponent(topicos3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtsangria, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSangria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fundoDadosLayout.setVerticalGroup(
            fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topicos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundoDadosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtdata)))
                .addGap(6, 6, 6)
                .addGroup(fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topicos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundoDadosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txthora)))
                .addGap(6, 6, 6)
                .addGroup(fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topicos2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundoDadosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtuser)))
                .addGap(6, 6, 6)
                .addGroup(fundoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topicos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundoDadosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtsangria)))
                .addGap(6, 6, 6)
                .addComponent(btnSangria)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        fundo.add(fundoDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, 190));

        menuLateral.setBackground(new java.awt.Color(248, 174, 176));

        Lgfundo.setBackground(new java.awt.Color(204, 204, 204));
        Lgfundo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LgNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LgNome.setText("Mourvan");

        LgAcesso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LgAcesso.setText("Administrador");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(40, 40));
        logo.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout LgfundoLayout = new javax.swing.GroupLayout(Lgfundo);
        Lgfundo.setLayout(LgfundoLayout);
        LgfundoLayout.setHorizontalGroup(
            LgfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LgfundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LgfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LgAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LgNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LgfundoLayout.setVerticalGroup(
            LgfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LgfundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LgfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LgfundoLayout.createSequentialGroup()
                        .addComponent(LgNome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LgAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        NBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        NBLogo.setMaximumSize(new java.awt.Dimension(80, 80));
        NBLogo.setPreferredSize(new java.awt.Dimension(80, 80));

        menuLTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menuLTitulo.setText("NewBig-System");

        btnClientes.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnFuncionarios.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnFuncionarios.setText("Funcionarios");
        btnFuncionarios.addActionListener(this::btnFuncionariosActionPerformed);

        btnCaixa.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.addActionListener(this::btnCaixaActionPerformed);

        javax.swing.GroupLayout menuLateralLayout = new javax.swing.GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lgfundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(NBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                        .addComponent(menuLTitulo)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                        .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
        menuLateralLayout.setVerticalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lgfundo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(menuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        if(caixa.verificarAbertura() == null){
            JOptionPane.showMessageDialog(
                    this,
                    "Não há caixa aberto!!!"
            );
        }
        else{
            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja mesmo fechar o caixa?"
            );
            if(resposta == JOptionPane.YES_OPTION){
                caixa.fechar(dadosUsuario.dadosCompletosFuncionario(3L)); /*alterar depois de fazer o login*/
                preencherValores();
            }
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        JSpinner input = new JSpinner(new SpinnerNumberModel(0.0, 0.0, 10000.0, 0.50));

        int opcao = JOptionPane.showConfirmDialog(
                null,
                input,
                "Digite o valor de abertura",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (opcao == JOptionPane.OK_OPTION) {
            double valor = (double) input.getValue();
            caixa.abrirCaixa(dadosUsuario.dadosCompletosFuncionario(3L), valor); /*Alterar depois de fazer o login*/
            preencherValores();
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnSangriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSangriaActionPerformed
        if(caixa.verificarAbertura() == null){
            JOptionPane.showMessageDialog(
                    this,
                    "Não há caixa aberto!!!"
            );
        }
        else{
            JSpinner input = new JSpinner(new SpinnerNumberModel(0.0, 0.0, 10000.0, 0.50));

            int opcao = JOptionPane.showConfirmDialog(
                    null,
                    input,
                    "Digite o valor de Sangria",
                    JOptionPane.OK_CANCEL_OPTION
            );

            if (opcao == JOptionPane.OK_OPTION) {
                double valor = (double) input.getValue();
                caixa.sangria(valor);
                JOptionPane.showMessageDialog(
                        this,
                        "Sangria de R$" + valor + "Concluida!!!"
                );
                preencherValores();
            }
        }
    }//GEN-LAST:event_btnSangriaActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        TelaCliente telaCliente = new TelaCliente();
        dispose();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        TelaFuncionario telaFuncionario = new TelaFuncionario();
        dispose();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        TelaCaixa telaCaixa = new TelaCaixa();
        dispose();
        telaCaixa.setVisible(true);
    }//GEN-LAST:event_btnCaixaActionPerformed


    public void preencherValores(){
        try{
            valorAtual.setText("R$" + caixa.getValorAtual());
            valorAbertura.setText("R$" + caixa.getValorAbertura());
            valorEntrada.setText("R$" + (caixa.getValorAtual() - caixa.getValorAbertura()));
            var dados = caixa.getObjeto();
            txtuser.setText(dados.getUsuarioAbertura().getNome());
            txtdata.setText(dados.getDataAbertura().toString());
            txthora.setText(dados.getHoraAbertura().toString());
            txtsangria.setText("R$" + caixa.getSangria());
        }catch (Exception e){
            valorAtual.setText("R$" + 0.00);
            valorAbertura.setText("R$" + 0.00);
            valorEntrada.setText("R$" + 0.00);
            txtuser.setText("null");
            txtdata.setText("null");
            txthora.setText("null");
            txtsangria.setText("R$" + 0.0);
        }
    }

    public void preencherLog(){
        LogsDeCaixaService logsDeCaixaService = new LogsDeCaixaService();
        var lista = logsDeCaixaService.lista();
        logs.setEditable(false);
        logs.setText("");
        for (int i = 0; i < lista.size(); i++){
            logs.setText(lista.get(i).getDescricao()+ " | " + lista.get(i).getData() + "\n" + logs.getText());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCaixa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LgAcesso;
    private javax.swing.JLabel LgNome;
    private javax.swing.JPanel Lgfundo;
    private javax.swing.JLabel NBLogo;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnSangria;
    private javax.swing.JPanel fundo;
    private javax.swing.JPanel fundoAbertura;
    private javax.swing.JPanel fundoDados;
    private javax.swing.JPanel fundoValorAtual;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextArea logs;
    private javax.swing.JLabel logsDoCaixa;
    private javax.swing.JLabel menuLTitulo;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel subtitulo1;
    private javax.swing.JLabel subtitulo2;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulocaixa;
    private javax.swing.JLabel topicos;
    private javax.swing.JLabel topicos1;
    private javax.swing.JLabel topicos2;
    private javax.swing.JLabel topicos3;
    private javax.swing.JLabel txtdata;
    private javax.swing.JLabel txthora;
    private javax.swing.JLabel txtsangria;
    private javax.swing.JLabel txtuser;
    private javax.swing.JLabel valorAbertura;
    private javax.swing.JLabel valorAtual;
    private javax.swing.JLabel valorEntrada;
    // End of variables declaration//GEN-END:variables
}
