/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view;

import com.newBig.system.repository.BatchRepository;
import com.newBig.system.repository.CustomizerFactory;
import com.newBig.system.repository.ProductRepository;
import com.newBig.system.repository.StockMovementRepository;
import com.newBig.system.service.*;
import jakarta.persistence.EntityManager;

import javax.swing.*;
import java.awt.*;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author mourv
 */
public class TelaInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicio.class.getName());
    Login login = new Login();
    private HelpService helpService;
    /**
     * Creates new form TelaInicio
     */
    public TelaInicio(HelpService helpService) {
        this.helpService = helpService;
        initComponents();
        logoUsuario();
        logoNewBig();
        bannerFun();
        preencherNome();
        dataHora();
        VendaDoDia();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLateral = new javax.swing.JPanel();
        NBLogo = new javax.swing.JLabel();
        menuLTitulo = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        btnCaixa = new javax.swing.JButton();
        btnClientes1 = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnLote = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        LgNome = new javax.swing.JLabel();
        LgAcesso = new javax.swing.JLabel();
        fundo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        TituloUsuario = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtVendaDia = new javax.swing.JLabel();
        CardTitulo1 = new javax.swing.JLabel();
        txthora = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        MenuBarra = new javax.swing.JMenuBar();
        menuBar = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        menuLateral.setBackground(new java.awt.Color(251, 227, 228));

        NBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        NBLogo.setMaximumSize(new java.awt.Dimension(80, 80));
        NBLogo.setPreferredSize(new java.awt.Dimension(80, 80));

        menuLTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menuLTitulo.setText("NewBig-System");

        btnInicio.setBackground(new java.awt.Color(253, 238, 239));
        btnInicio.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        btnFuncionarios.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnFuncionarios.setText("Funcionarios");
        btnFuncionarios.addActionListener(this::btnFuncionariosActionPerformed);

        btnCaixa.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.addActionListener(this::btnCaixaActionPerformed);

        btnClientes1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnClientes1.setText("Clientes");
        btnClientes1.addActionListener(this::btnClientes1ActionPerformed);

        btnVenda.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnVenda.setText("Venda");
        btnVenda.addActionListener(this::btnVendaActionPerformed);

        btnProduto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnProduto.setText("Produtos");
        btnProduto.addActionListener(this::btnProdutoActionPerformed);

        btnLote.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnLote.setText("Lote");
        btnLote.addActionListener(this::btnLoteActionPerformed);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(40, 40));
        logo.setPreferredSize(new java.awt.Dimension(40, 40));

        LgNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LgNome.setText("Mourvan");

        LgAcesso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LgAcesso.setText("Administrador");

        javax.swing.GroupLayout menuLateralLayout = new javax.swing.GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(menuLTitulo)
                .addGap(47, 47, 47))
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(NBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLateralLayout.createSequentialGroup()
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LgAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LgNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFuncionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClientes1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLateralLayout.setVerticalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLote, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addComponent(LgNome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LgAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fundo.setBackground(new java.awt.Color(255, 249, 249));
        fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Titulo.setText("Bem Vindo!!!");
        fundo.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        TituloUsuario.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        TituloUsuario.setText("Usuario");
        fundo.add(TituloUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 260, -1));

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner.png"))); // NOI18N
        banner.setMinimumSize(new java.awt.Dimension(200, 200));
        fundo.add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 720, 200));

        jPanel2.setBackground(new java.awt.Color(253, 238, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtVendaDia.setFont(new java.awt.Font("Arial", 0, 120)); // NOI18N
        txtVendaDia.setText("0");

        CardTitulo1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        CardTitulo1.setText("Vendas do Dia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(CardTitulo1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtVendaDia)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CardTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtVendaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        fundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 230, 200));

        txthora.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        txthora.setText("00:00:00");
        fundo.add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 410, 60));

        txtData.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        txtData.setText("00/00/0000");
        fundo.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 310, 60));

        menuBar.setText("Menu");

        menuLogin.setText("Login");
        menuLogin.addActionListener(this::menuLoginActionPerformed);
        menuBar.add(menuLogin);

        menuSair.setText("Sair");
        menuSair.addActionListener(this::menuSairActionPerformed);
        menuBar.add(menuSair);

        MenuBarra.add(menuBar);

        setJMenuBar(MenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        TelaInicio tela = new TelaInicio(this.helpService);
        dispose();
        tela.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        TelaFuncionario telaFuncionario = new TelaFuncionario(this.helpService);
        dispose();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        TelaCaixa telaCaixa = new TelaCaixa(this.helpService);
        dispose();
        telaCaixa.setVisible(true);
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientes1ActionPerformed
        TelaCliente telaCliente = new TelaCliente(this.helpService);
        dispose();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_btnClientes1ActionPerformed

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        SalesView salesView = new SalesView(this.helpService);
        dispose();
        salesView.setVisible(true);
    }//GEN-LAST:event_btnVendaActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        ProductView productView = new ProductView(this.helpService);
        dispose();
        productView.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoteActionPerformed
        ArrivalBatchView arrivalBatchView = new ArrivalBatchView(this.helpService);
        dispose();
        arrivalBatchView.setVisible(true);
    }//GEN-LAST:event_btnLoteActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        Caixa caixa = new Caixa();
        if(caixa.verificarAbertura() != null){
            JOptionPane.showMessageDialog(
                    this,
                    "Não é possivel encerrar o sistema!! Caixa está aberto"
            );
            TelaCaixa telaCaixa = new TelaCaixa(this.helpService);
            dispose();
            telaCaixa.setVisible(true);
        }
        else{
            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja mesmo encerrar o sistema?"
            );
            if(resposta == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        Caixa caixa = new Caixa();
        TelaLogin telaLogin = new TelaLogin(this.helpService);
        if(caixa.verificarAbertura() != null){
            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Possui um caixa em aberto, deseja trocar de Login?"
            );
            if(resposta == JOptionPane.YES_OPTION){
                dispose();
                telaLogin.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(
                    this,
                    "Encerrado login!!!"
            );
            dispose();
            telaLogin.setVisible(true);
        }
    }//GEN-LAST:event_menuLoginActionPerformed

    public void VendaDoDia(){
        int n = VendasDia.getVendaDia();
        txtVendaDia.setText(String.valueOf(n));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // temporario

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicio(new HelpService()).setVisible(true));
    }

    /*Funcões menu lateral*/

    public void logoUsuario(){
        ImageIcon icon = (ImageIcon) logo.getIcon();
        Image imagem = icon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        logo.setIcon(new ImageIcon(imagem));
        LgNome.setText(login.nomeLog());
        LgAcesso.setText(login.acessoLog());
    }

    public void logoNewBig(){
        ImageIcon icon = (ImageIcon) NBLogo.getIcon();
        Image imagem = icon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        NBLogo.setIcon(new ImageIcon(imagem));
    }

    public void bannerFun(){
        ImageIcon icon = (ImageIcon) banner.getIcon();
        Image imagem = icon.getImage().getScaledInstance(700, 220, Image.SCALE_SMOOTH);
        banner.setIcon(new ImageIcon(imagem));
    };

    public void preencherNome(){
        TituloUsuario.setText(login.nomeLog());
    }

    public void dataHora(){
        txtData.setText(LocalDate.now().toString());
        DateTimeFormatter modelo = DateTimeFormatter.ofPattern("HH:mm:ss");

        Timer timer = new Timer(1000, e -> {
            txthora.setText(LocalTime.now().format(modelo).toString());
        });
        timer.start();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CardTitulo1;
    private javax.swing.JLabel LgAcesso;
    private javax.swing.JLabel LgNome;
    private javax.swing.JMenuBar MenuBarra;
    private javax.swing.JLabel NBLogo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloUsuario;
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnClientes1;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLote;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnVenda;
    private javax.swing.JPanel fundo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JMenu menuBar;
    private javax.swing.JLabel menuLTitulo;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtVendaDia;
    private javax.swing.JLabel txthora;
    // End of variables declaration//GEN-END:variables
}
