/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view;

import com.newBig.system.repository.ClienteRepo;
import com.newBig.system.repository.CustomizerFactory;
import com.newBig.system.service.Login;
import jakarta.persistence.EntityManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author MH
 */
public class TelaCliente extends JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCliente.class.getName());
    TelaClientesAtualizar telaClientesAtualizar = new TelaClientesAtualizar();
    TelaFormularioCliente telaFormularioCliente = new TelaFormularioCliente();
    TelaDadosCliente telaDadosCliente = new TelaDadosCliente();
    Login login = new Login();
    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        logoUsuario();
        logoNewBig();
        this.setLocationRelativeTo(null);
        TabelaClientes.setRowHeight(22);
        rdNome.setSelected(true);
        LgNome.setText(login.nomeLog());
        LgAcesso.setText(login.acessoLog());
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new JMenu();
        clienteRadioGroup = new ButtonGroup();
        menuLateral = new JPanel();
        Lgfundo = new JPanel();
        LgNome = new JLabel();
        LgAcesso = new JLabel();
        logo = new JLabel();
        NBLogo = new JLabel();
        menuLTitulo = new JLabel();
        btnClientes = new JButton();
        btnFuncionarios = new JButton();
        btnCaixa = new JButton();
        fundo = new JPanel();
        tituloclientes = new JLabel();
        jScrollPane1 = new JScrollPane();
        TabelaClientes = new JTable();
        btnNovo = new JButton();
        btnAtualizar = new JButton();
        btnDeletar = new JButton();
        TxtBuscar = new JTextField();
        btnBuscar = new JButton();
        btnDados = new JButton();
        rdNome = new JRadioButton();
        rdCpf = new JRadioButton();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        jMenu2 = new JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("NewBig-Cadastro-Cliente");

        menuLateral.setBackground(new Color(248, 174, 176));

        Lgfundo.setBackground(new Color(204, 204, 204));
        Lgfundo.setBorder(BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LgNome.setFont(new Font("Arial", 1, 14)); // NOI18N
        LgNome.setText("Mourvan");

        LgAcesso.setFont(new Font("Arial", 0, 12)); // NOI18N
        LgAcesso.setText("Administrador");

        logo.setIcon(new ImageIcon(getClass().getResource("/images/avatar.png"))); // NOI18N
        logo.setMaximumSize(new Dimension(40, 40));
        logo.setPreferredSize(new Dimension(40, 40));

        GroupLayout LgfundoLayout = new GroupLayout(Lgfundo);
        Lgfundo.setLayout(LgfundoLayout);
        LgfundoLayout.setHorizontalGroup(
            LgfundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, LgfundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LgfundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(LgAcesso, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                    .addComponent(LgNome, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LgfundoLayout.setVerticalGroup(
            LgfundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, LgfundoLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LgfundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(logo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(LgfundoLayout.createSequentialGroup()
                        .addComponent(LgNome, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LgAcesso, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        NBLogo.setIcon(new ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        NBLogo.setMaximumSize(new Dimension(80, 80));
        NBLogo.setPreferredSize(new Dimension(80, 80));

        menuLTitulo.setFont(new Font("Arial", 1, 14)); // NOI18N
        menuLTitulo.setText("NewBig-System");

        btnClientes.setFont(new Font("Bahnschrift", 1, 14)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnFuncionarios.setFont(new Font("Bahnschrift", 1, 14)); // NOI18N
        btnFuncionarios.setText("Funcionarios");
        btnFuncionarios.addActionListener(this::btnFuncionariosActionPerformed);

        btnCaixa.setFont(new Font("Bahnschrift", 1, 14)); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.addActionListener(this::btnCaixaActionPerformed);

        GroupLayout menuLateralLayout = new GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
            menuLateralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGroup(menuLateralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lgfundo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(NBLogo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(menuLateralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                        .addComponent(menuLTitulo)
                        .addGap(47, 47, 47))
                    .addGroup(GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                        .addComponent(btnClientes, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGroup(menuLateralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(btnFuncionarios, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCaixa, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
        menuLateralLayout.setVerticalGroup(
            menuLateralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NBLogo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLTitulo)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClientes, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFuncionarios, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCaixa, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lgfundo, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fundo.setBackground(new Color(255, 255, 255));

        tituloclientes.setFont(new Font("Unispace", 1, 14)); // NOI18N
        tituloclientes.setText("Clientes");

        TabelaClientes.setFont(new Font("Unispace", 0, 14)); // NOI18N
        TabelaClientes.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                Long.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaClientes);
        if (TabelaClientes.getColumnModel().getColumnCount() > 0) {
            TabelaClientes.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        btnNovo.setBackground(new Color(153, 255, 153));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        btnAtualizar.setBackground(new Color(255, 255, 153));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        btnDeletar.setBackground(new Color(255, 102, 102));
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(this::btnDeletarActionPerformed);

        TxtBuscar.setToolTipText("");
        TxtBuscar.addActionListener(this::TxtBuscarActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnDados.setBackground(new Color(51, 153, 255));
        btnDados.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        btnDados.setText("Dados Adicionais");
        btnDados.addActionListener(this::btnDadosActionPerformed);

        clienteRadioGroup.add(rdNome);
        rdNome.setFont(new Font("Arial", 0, 12)); // NOI18N
        rdNome.setText("Nome");
        rdNome.addActionListener(this::rdNomeActionPerformed);

        clienteRadioGroup.add(rdCpf);
        rdCpf.setFont(new Font("Arial", 0, 12)); // NOI18N
        rdCpf.setText("CPF");

        GroupLayout fundoLayout = new GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(fundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addGroup(fundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(fundoLayout.createSequentialGroup()
                                .addComponent(tituloclientes, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdNome)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdCpf)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtBuscar, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 703, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeletar)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDados)
                        .addGap(46, 46, 46))))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(fundoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloclientes)
                    .addComponent(TxtBuscar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(rdNome)
                    .addComponent(rdCpf, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fundoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btnDados, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovo, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAtualizar, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeletar, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLateral, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(menuLateral, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fundo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        telaFormularioCliente.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        int linha = TabelaClientes.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(
                    this,
                    "Nenhum cliente selecionado!!"

            );
        }
        else{
            Long id = (Long) TabelaClientes.getValueAt(linha, 0);
            telaClientesAtualizar.preencher(id);
            telaClientesAtualizar.setVisible(true);
        }


    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int linha = TabelaClientes.getSelectedRow();
        Long id = (Long) TabelaClientes.getValueAt(linha, 0);
        String nome = (String) TabelaClientes.getValueAt(linha, 1);
        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja mesmo apagar o cliente " + nome +"?"
        );
        if(resposta == JOptionPane.YES_OPTION){
            EntityManager em = CustomizerFactory.getEntityManager(); /*Pegar objeto que conecta com o banco*/
            ClienteRepo dados = new ClienteRepo(em);
            dados.delete(dados.SelecionarCliente(id));
            preencherTabela();

        }
    }

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          

    }


    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        int linha = TabelaClientes.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(
                    this,
                    "Nenhum cliente selecionado!!"

            );
        }
        else{
            Long id = (Long) TabelaClientes.getValueAt(linha, 0);
            telaDadosCliente.setVisible(true);
            telaDadosCliente.dadosCliente(id);
        }
    }//GEN-LAST:event_btnDadosActionPerformed

    private void rdNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNomeActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(rdNome.isSelected()){
            preencherNome();
        }
        else if(rdCpf.isSelected()){
            preencherCpf();
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        TelaCliente telaCliente = new TelaCliente();
        dispose();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        TelaFuncionario telaFuncionario = new TelaFuncionario();
        dispose();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        TelaCaixa telaCaixa = new TelaCaixa();
        dispose();
        telaCaixa.setVisible(true);
    }//GEN-LAST:event_btnCaixaActionPerformed


    /*Funcões menu lateral*/

    public void logoUsuario(){
        ImageIcon icon = (ImageIcon) logo.getIcon();
        Image imagem = icon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        logo.setIcon(new ImageIcon(imagem));
    }

    public void logoNewBig(){
        ImageIcon icon = (ImageIcon) NBLogo.getIcon();
        Image imagem = icon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        NBLogo.setIcon(new ImageIcon(imagem));
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> new TelaCliente().setVisible(true));

    }

    public void preencherTabela(){
        EntityManager em = CustomizerFactory.getEntityManager(); /*Pegar objeto que conecta com o banco*/
        ClienteRepo dados = new ClienteRepo(em);
        DefaultTableModel linha = (DefaultTableModel) TabelaClientes.getModel();
        linha.setRowCount(0);
        var lista = dados.BuscaCliente();
        for (int i = 0; i < lista.size() ; i++) {
            linha.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getCpf(),
            });
        }
    }

    public void preencherNome(){
        EntityManager em = CustomizerFactory.getEntityManager(); /*Pegar objeto que conecta com o banco*/
        ClienteRepo dados = new ClienteRepo(em);
        DefaultTableModel linha = (DefaultTableModel) TabelaClientes.getModel();
        linha.setRowCount(0);
        String nome = TxtBuscar.getText();
        var lista = dados.BuscaPorNome(nome);
        for (int i = 0; i < lista.size() ; i++) {
            linha.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getCpf(),
            });
        }
    }

    public void preencherCpf(){
        EntityManager em = CustomizerFactory.getEntityManager(); /*Pegar objeto que conecta com o banco*/
        ClienteRepo dados = new ClienteRepo(em);
        DefaultTableModel linha = (DefaultTableModel) TabelaClientes.getModel();
        linha.setRowCount(0);
        String cpf = TxtBuscar.getText();
        var lista = dados.BuscaPorCPF(cpf);
        for (int i = 0; i < lista.size() ; i++) {
            linha.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getCpf(),
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel LgAcesso;
    private JLabel LgNome;
    private JPanel Lgfundo;
    private JLabel NBLogo;
    private JTable TabelaClientes;
    private JTextField TxtBuscar;
    private JButton btnAtualizar;
    private JButton btnBuscar;
    private JButton btnCaixa;
    private JButton btnClientes;
    private JButton btnDados;
    private JButton btnDeletar;
    private JButton btnFuncionarios;
    private JButton btnNovo;
    private ButtonGroup clienteRadioGroup;
    private JPanel fundo;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenu jMenu3;
    private JMenuBar jMenuBar1;
    private JScrollPane jScrollPane1;
    private JLabel logo;
    private JLabel menuLTitulo;
    private JPanel menuLateral;
    private JRadioButton rdCpf;
    private JRadioButton rdNome;
    private JLabel tituloclientes;
    // End of variables declaration//GEN-END:variables
}
