/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.newBig.system.view.funcionario;

import com.newBig.system.controller.HelpController;
import com.newBig.system.model.service.usuario.impl.CadastroUsuario;

import javax.swing.*;

/**
 *
 * @author MH
 */
public class TelaCadastroFuncionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName());
    HelpController helpController;
    /**
     * Creates new form TelaCadastroFuncionario
     */
    public TelaCadastroFuncionario(HelpController helpController) {
        initComponents();
        this.helpController = helpController;
        this.setLocationRelativeTo(null);
        Long id = helpController.getUsuarioController().lastIdFun();
        txtId.setText(String.valueOf(id + 1));
        txtId.setEnabled(false);
        rdSem.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        Acesso = new javax.swing.ButtonGroup();
        fundo = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        divisa = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        rdSem = new javax.swing.JRadioButton();
        lblSenha1 = new javax.swing.JLabel();
        rdAdm = new javax.swing.JRadioButton();
        rdOperador = new javax.swing.JRadioButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fundo.setBackground(new java.awt.Color(255, 249, 249));
        fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("Nome");
        fundo.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));
        fundo.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 30));
        fundo.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 260, 30));

        lblCpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCpf.setText("CPF");
        fundo.add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));
        fundo.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 260, 30));

        lblLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLogin.setText("Login");
        fundo.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        divisa.setBackground(new java.awt.Color(251, 227, 228));
        divisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Titulo.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        Titulo.setText("Cadastro Funcionario");

        javax.swing.GroupLayout divisaLayout = new javax.swing.GroupLayout(divisa);
        divisa.setLayout(divisaLayout);
        divisaLayout.setHorizontalGroup(
            divisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divisaLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(292, 292, 292))
        );
        divisaLayout.setVerticalGroup(
            divisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fundo.add(divisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 70));

        btnEnviar.setBackground(new java.awt.Color(153, 255, 153));
        btnEnviar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);
        fundo.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 120, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        fundo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 120, 40));

        lblSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSenha.setText("Acesso");
        fundo.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        lblId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblId.setText("ID");
        fundo.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        txtId.setActionCommand("<Not Set>");
        fundo.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 260, 30));

        txtSenha.addActionListener(this::txtSenhaActionPerformed);
        fundo.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 260, 30));

        Acesso.add(rdSem);
        rdSem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdSem.setText("Sem acesso");
        rdSem.addActionListener(this::rdSemActionPerformed);
        fundo.add(rdSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 150, 40));

        lblSenha1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSenha1.setText("Senha");
        fundo.add(lblSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        Acesso.add(rdAdm);
        rdAdm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdAdm.setText("Administrador");
        rdAdm.addActionListener(this::rdAdmActionPerformed);
        fundo.add(rdAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 150, 40));

        Acesso.add(rdOperador);
        rdOperador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdOperador.setSelected(true);
        rdOperador.setText("Operador");
        rdOperador.addActionListener(this::rdOperadorActionPerformed);
        fundo.add(rdOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        try{
            String nome = txtNome.getText();
            String cpf = txtCpf.getText();
            String login = txtLogin.getText();
            int senha = Integer.parseInt(txtSenha.getText());
            int acesso = 3;
            if(rdAdm.isSelected()){
                acesso = 1;
            } else if (rdOperador.isSelected()) {
                acesso = 2;
            }
            if(nome.isEmpty() || cpf.isEmpty() || login.isEmpty()){
                throw new Exception("Campo não preenchido!");
            }
            if (cpf.matches(".*[\\p{L}].*")) {
                throw new Exception("CPF contém letras");
            }

            helpController.getUsuarioController().registerNewFuncionario(nome, cpf, acesso, login, senha);

            JOptionPane.showMessageDialog(
                    this,
                    "Funcionario cadastrado com sucesso!!"
            );
            dispose();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao cadastrar Funcionario confira os dados!!!! " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void rdSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSemActionPerformed

    private void rdAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAdmActionPerformed

    private void rdOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOperadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdOperadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroFuncionario(new HelpController()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Acesso;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JPanel divisa;
    private javax.swing.JPanel fundo;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenha1;
    private javax.swing.JRadioButton rdAdm;
    private javax.swing.JRadioButton rdOperador;
    private javax.swing.JRadioButton rdSem;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
